<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="application/xml" href="haoussa_v4.xsl"?>

<!-- 
Auteurs version papier : projet SouTéBa
Rédacteur en chef : Laouali Amani
Lexicographes : Abdou Sanda, Aboubacar Noma Chaibou, Alio Mainassara, Jaharou Souley, Laouali Amani
Responsable principal : Thomas Büttner
Coordinateur académique : Mallam Garba Maman

Auteurs version XML : projet DiLAF
Coordinatrice : Chantal Enguehard
Responsable informatique 2010-2016 : Mathieu Mangeot

Publication de référence : Mathieu Mangeot & Chantal Enguehard (2013) Des dictionnaires éditoriaux aux représentations XML standardisées. Chaptre 8, livre "Ressources Lexicales : contenu, construction, utilisation, évaluation", Eds. Nuria Gala & Michael Zock, Linguisticae Investigationes Supplementa, John Benjamins Publishing, Amsterdam, Pays-Bas, 24 p.

Date : 25/07/2017
Version : 1.3
Licence : Creative Commons - Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 3.0 France (CC BY-NC-SA 3.0 FR) : https://creativecommons.org/licenses/by-nc-sa/3.0/fr/

-->
<!DOCTYPE dilaf [
<!ELEMENT dilaf (source, article*)>
<!ATTLIST dilaf src CDATA #REQUIRED>
<!ATTLIST dilaf trg CDATA #REQUIRED>
<!ATTLIST dilaf version CDATA #REQUIRED>
<!ATTLIST dilaf datecreation CDATA #REQUIRED>

<!ELEMENT source (ref*, titre, auteurs, avertissement, license)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (#PCDATA)>
<!ELEMENT avertissement (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license lien CDATA #IMPLIED>

<!ELEMENT article (kalma, furici, nau_i?, jinsi?, mace*, jam_i*, siffolin_kalma?, yare?, rukunin_ma_ana*)>
<!ATTLIST article id ID #REQUIRED>

<!ELEMENT kalma (#PCDATA)>
<!ELEMENT furici (#PCDATA)>
<!ELEMENT nau_i (#PCDATA)>
<!ELEMENT jinsi (#PCDATA)>
<!ELEMENT mace (item+)>
<!ELEMENT jam_i (item+)>
<!ELEMENT siffolin_kalma (item+)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT yare (item+)>

<!ELEMENT rukunin_ma_ana (ma_ana?, misali*, salon_magana*, makwatanci*, kishiyar_kalma*, syn*)>
<!ATTLIST rukunin_ma_ana id ID #REQUIRED>
<!ATTLIST rukunin_ma_ana num CDATA #IMPLIED>


<!ELEMENT ma_ana (#PCDATA)>
<!ELEMENT misali (#PCDATA)>
<!ELEMENT makwatanci (#PCDATA)>
<!ATTLIST makwatanci lang (far) #REQUIRED>

<!ELEMENT kishiyar_kalma (#PCDATA)>
<!ATTLIST kishiyar_kalma raga IDREF #IMPLIED>
<!ATTLIST kishiyar_kalma num CDATA #IMPLIED>

<!ELEMENT syn (#PCDATA)>
<!ATTLIST syn raga IDREF #IMPLIED>
<!ATTLIST syn num CDATA #IMPLIED>

<!ELEMENT salon_magana (misalin_salo, bayyani?)>
<!ELEMENT misalin_salo (#PCDATA)>
<!ELEMENT bayyani (#PCDATA)>
]>
<dilaf src="hau" trg="fra" version="1.3" datecreation="25/07/2017">

<source>
	<ref>Soutéba. Dictionnaire haoussa-français. Enseignement du cycle de base 1, 2007</ref>
	<titre>Dictionnaire haoussa-français.</titre>
	<auteurs>Projet Soutien à l'Education de Base (Soutéba)</auteurs>
	<avertissement>Ce document est protégé par une licence Creative commons Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0). Il est obligatoire d'insérer dans les copies, extraits et versions modifiées de ce fichier le texte suivant : "Ressource issue du dictionnaire dilaf_hau_fra_v1.3.xml hébergée par le site web DiLAF www.dilaf.org. Il est interdit de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier sans faire mention de la même licence ; il est interdit d'utiliser commercialement les informations issues de ce fichier, des copies de ce fichier et des versions modifiées de ce fichier. Il est autorisé de copier ce fichier, de modifier ce fichier, de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier à condition de le faire avec la même licence.</avertissement>
	<license lien="https://creativecommons.org/licenses/by-nc-sa/2.0/">
	</license>
</source>

<article id="a1">
	<kalma>a</kalma>
	<furici>áa</furici>
	<nau_i>s.</nau_i>
	<rukunin_ma_ana id="a1_1" num="1">
		<ma_ana>Harafi na biyu a cikin haruffan hausa.</ma_ana>
		<misali>Sunan Ado yana farawa da a.</misali>
		<makwatanci lang="far">voyelle a</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="a2">
	<kalma>a</kalma>
	<furici>á</furici>
	<nau_i>ws.</nau_i>
	<rukunin_ma_ana id="a2_1" num="1">
		<ma_ana>kalmar nahawu mai ɗaukar matsayin suna.</ma_ana>
		<misali>A tafi a gani in yana nan.</misali>
		<makwatanci lang="far">on</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="a_ƙalla1">
	<kalma>a ƙalla</kalma>
	<furici>à ƙállàa</furici>
	<nau_i>nu.</nau_i>
	<rukunin_ma_ana id="a_ƙalla1_1" num="1">
		<ma_ana>ƙaramin lissafi.</ma_ana>
		<misali>A ƙalla mutum ɗari sun taru ƙofar gidan sarki.</misali>
		<makwatanci lang="far">au moins</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="a_nan1">
	<kalma>a nan</kalma>
	<furici>à nán</furici>
	<nau_i>nuw.</nau_i>
	<rukunin_ma_ana id="a_nan1_1" num="1">
		<ma_ana>wuri na kusa da mai magana.</ma_ana>
		<misali>A nan muka bar shi.</misali>
		<makwatanci lang="far">ici</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="a_a1">
	<kalma>a'a</kalma>
	<furici>áa'á</furici>
	<nau_i>s.</nau_i>
	<rukunin_ma_ana id="a_a1_1" num="1">
		<ma_ana>kalmar ƙi ko rishin yarda da wani abu, kenan kalmar a'antawa.</ma_ana>
		<misali>A'a, ku tafi ba ya zuwa.</misali>
		<makwatanci lang="far">non</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="a_a2">
	<kalma>a'a</kalma>
	<furici>àa' á</furici>
	<nau_i>nuh.</nau_i>
	<rukunin_ma_ana id="a_a2_1" num="1">
		<ma_ana>kalmar nuna mamaki.</ma_ana>
		<misali>A'a, ya ɓace maku!.</misali>
		<makwatanci lang="far">mot exprimant le dégoût ou l'étonnement</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abacada1">
	<kalma>abacada</kalma>
	<furici>ábácádà</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="abacada1_1" num="1">
		<ma_ana>jimilar baƙaƙe da wasulla waɗanda ake amfani da su wajen rubuta harshe.</ma_ana>
		<misali>Abacada ta hausa ta ƙunshi haruffa 37.</misali>
		<makwatanci lang="far">alphabet</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abada1">
	<kalma>abada</kalma>
	<furici>ábàdáa</furici>
	<nau_i>nul.</nau_i>
	<rukunin_ma_ana id="abada1_1" num="1">
		<ma_ana>kalma mai nuna abin da ba ya taɓa faruwa ba.</ma_ana>
		<misali>Abada ba a kiran shi ya amsa.</misali>
		<makwatanci lang="far">jamais</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abara1">
	<kalma>abara</kalma>
	<furici>ábáráa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<yare>
		<item>tantabara</item>
	</yare>
	<rukunin_ma_ana id="abara1_1" num="1">
		<ma_ana>tsuntsun gida mai kamar habjiya.</ma_ana>
		<misali>Abara ta jefa ƙwai cikin kasko.</misali>
		<makwatanci lang="far">pigeon</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abara2">
	<kalma>abara</kalma>
	<furici>ábáráa</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="abara2_1" num="1">
		<ma_ana>sunan wani irin jirgin ruwa ne.</ma_ana>
		<makwatanci lang="far">variété de pirogue</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abarba1">
	<kalma>abarba</kalma>
	<furici>àbàrbá</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="abarba1_1" num="1">
		<ma_ana>wani irin ɗiyan ice mai zaƙi da ake noma a ƙasar Kurmi.</ma_ana>
		<misali>In za a cin abarba sai an feɗe ta, an fidda fatarta.</misali>
		<makwatanci lang="far">ananas</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abawa1">
	<kalma>abawa</kalma>
	<furici>ábàawáa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="abawa1_1" num="1">
		<ma_ana>zare mai kabri wanda ake yi da mazari.</ma_ana>
		<misali>Abawa ba ya da daɗin yin ɗinki.</misali>
		<makwatanci lang="far">sorte de fil fait à la main</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abba1">
	<kalma>abba</kalma>
	<furici>ábbà</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<mace>
		<item>inna</item>
	</mace>
	<rukunin_ma_ana id="abba1_1" num="1">
		<ma_ana>sunan da yaro ke yi wa mahaifinsa.</ma_ana>
		<misali>Abba ya haife mu, shi yake lura da mu.</misali>
		<makwatanci lang="far">papa</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abinci1">
	<kalma>abinci</kalma>
	<furici>àbíncí</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="abinci1_1" num="1">
		<ma_ana>duk irin abin da ake iya ci.</ma_ana>
		<misali>Musa yana cin abinci.</misali>
		<makwatanci lang="far">nourriture</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="aboki1">
	<kalma>aboki</kalma>
	<furici>àbóokíi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<mace>
		<item>abokiya</item>
		<item>abukkiya</item>
	</mace>
	<jam_i>
		<item>abokai</item>
		<item>abukkai</item>
	</jam_i>
	<rukunin_ma_ana id="aboki1_1" num="1">
		<ma_ana>mutum wanda ake rayuwa da shi cikin yarda da gane wa juna.</ma_ana>
		<misali>Cikin wahala ko cikin daɗi aboki yana da amfani.</misali>
		<makwatanci lang="far">ami, compagnon, camarade</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abokin_ango1">
	<kalma>abokin ango</kalma>
	<furici>àbóokìn ángòo</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>abokan ango</item>
	</jam_i>
	<rukunin_ma_ana id="abokin_ango1_1" num="1">
		<ma_ana>mutum na kusa da ango, mai taimaka masa har ƙarewar shagalin aure.</ma_ana>
		<misali>Abokin ango ya kawo goron aure.</misali>
		<makwatanci lang="far">garçon d'honneur</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abokin_hamayya1">
	<kalma>abokin hamayya</kalma>
	<furici>àbóokínhàamáyyàa</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<mace>
		<item>abokiyar hamayya</item>
	</mace>
	<jam_i>
		<item>abokan hamayya</item>
	</jam_i>
	<rukunin_ma_ana id="abokin_hamayya1_1" num="1">
		<ma_ana>mutumen da ake kokowar samun wani abu da shi.</ma_ana>
		<misali>Abokin hamayya ba ya rufin asiri.</misali>
		<makwatanci lang="far">rival, adversaire</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abokin_wasiƙa1">
	<kalma>abokin wasiƙa</kalma>
	<furici>àbóokìn wàsíikàa</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<mace>
		<item>abokiyar wasiƙa</item>
	</mace>
	<jam_i>
		<item>abokan wasiƙa</item>
	</jam_i>
	<rukunin_ma_ana id="abokin_wasiƙa1_1" num="1">
		<ma_ana>mutumen da ake rubuta wa juna wasiƙa da shi.</ma_ana>
		<misali>Jadi abokin wasiƙa ta ne, yana rubuta mini, ina rubuta masa.</misali>
		<makwatanci lang="far">correspondant</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abokiyar_amarya1">
	<kalma>abokiyar amarya</kalma>
	<furici>àboókìyárámáryáa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<jam_i>
		<item>abukan amarya</item>
	</jam_i>
	<rukunin_ma_ana id="abokiyar_amarya1_1" num="1">
		<ma_ana>budurwa mai zama kusa da amarya, ta taimaka mata har ta je gidan mijinta.</ma_ana>
		<misali>Abokiyar amarya tana yi wa amarya ɗafe.</misali>
		<makwatanci lang="far">fille d'honneur</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abu1">
	<kalma>abu</kalma>
	<furici>àbù</furici>
	<nau_i>s.</nau_i>
	<mace>
		<item>aba</item>
	</mace>
	<jam_i>
		<item>abubuwa</item>
		<item>ababe</item>
	</jam_i>
	<rukunin_ma_ana id="abu1_1" num="1">
		<ma_ana>komi ne wanda ake iya ba suna nan take.</ma_ana>
		<misali>Abu ya zo da kyau.</misali>
		<makwatanci lang="far">chose</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abuta1">
	<kalma>abuta</kalma>
	<furici>àbùutáa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="abuta1_1" num="1">
		<ma_ana>halin zama tare da aboki.</ma_ana>
		<misali>Wata abuta ta fi zumunci.</misali>
		<makwatanci lang="far">camaraderie, amitié</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="abzin1">
	<kalma>abzin</kalma>
	<furici>ábzìn</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="abzin1_1" num="1">
		<ma_ana>wani sashe ne na jahar Agadas.</ma_ana>
		<misali>A Abzin ana kiwon raƙumma da noman dabino.</misali>
		<makwatanci lang="far">région de l'Aïr</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="acaka1">
	<kalma>acaka</kalma>
	<furici>àcákáa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<yare>
		<item>asaka</item>
	</yare>
	<rukunin_ma_ana id="acaka1_1" num="1">
		<ma_ana>sunan wata irin rawa ce wadda ake juyawa sosai, in ana yin ta.</ma_ana>
		<misali>Rawar acaka sai mai jin ƙarfi ke yin ta.</misali>
		<makwatanci lang="far">nom d'une danse</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="ada1">
	<kalma>ada</kalma>
	<furici>áadáa</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="ada1_1" num="1">
		<ma_ana>sunan wani irin malam batata ne mai jiki ja-ja da toka-toka.</ma_ana>
		<misali>Yara sun shiga cikin fure suna neman ada.</misali>
		<makwatanci lang="far">papillon gris-marron</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adabali1">
	<kalma>adabali</kalma>
	<furici>ádábàlíi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>adabalai</item>
	</jam_i>
	<rukunin_ma_ana id="adabali1_1" num="1">
		<ma_ana>shaidar jin ciwo ko wurin da ƙurji ya warke.</ma_ana>
		<misali>Raƙumin nan na da adabali ga baya, inda aka yi masa wuta.</misali>
		<makwatanci lang="far">sorte de cicatrice</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adada1">
	<kalma>adada</kalma>
	<furici>àdàdáa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="adada1_1" num="1">
		<ma_ana>sunan wata irin rumfa ce, wadda ke da doro a tsakiyarta.</ma_ana>
		<misali>Adada rumfa ce mai wuyar hawa.</misali>
		<makwatanci lang="far">sorte de hangar</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adadi1">
	<kalma>adadi</kalma>
	<furici>ádàdíi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>adudda</item>
	</jam_i>
	<rukunin_ma_ana id="adadi1_1" num="1">
		<ma_ana>yawan ƙilgon.</ma_ana>
		<misali>Adadin mutanen da suka taru ya hamɓare.</misali>
		<makwatanci lang="far">nombre</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adadi2">
	<kalma>adadi</kalma>
	<furici>ádàdíi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="adadi2_1" num="1">
		<ma_ana>lokacin cika alkawalin da aka yi.</ma_ana>
		<misali>An ba ya adadin ya biya bashinsa.</misali>
		<makwatanci lang="far">échéance</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adaka1">
	<kalma>adaka</kalma>
	<furici>àdákàa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<jam_i>
		<item>adaku</item>
		<item>adakoki</item>
	</jam_i>
	<rukunin_ma_ana id="adaka1_1" num="1">
		<ma_ana>ma'ajiyar sa tufafi ta katako ko ƙarfe.</ma_ana>
		<misali>Adaka wadda aka sa wa kayan amarya ta cika.</misali>
		<makwatanci lang="far">caisse, malle, cantine</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adalci1">
	<kalma>adalci</kalma>
	<furici>áadálcìi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="adalci1_1" num="1">
		<ma_ana>halin yin abin gaskiya.</ma_ana>
		<misali>Adalcinsa ya sa aka ba ya ikon ƙasar nan.</misali>
		<makwatanci lang="far">justice</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adali1">
	<kalma>adali</kalma>
	<furici>áadàlíi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>adalai</item>
	</jam_i>
	<rukunin_ma_ana id="adali1_1" num="1">
		<ma_ana>mutum mai yin abin da ke na gaskiya.</ma_ana>
		<misali>Da wuya a sami ɗan siyasa adali.</misali>
		<makwatanci lang="far">juste</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adana1">
	<kalma>adana</kalma>
	<furici>áadànáa</furici>
	<nau_i>aik.</nau_i>
	<siffolin_kalma>
		<item>adane</item>
		<item>adani</item>
		<item>adano</item>
		<item>adanu</item>
	</siffolin_kalma>
	<rukunin_ma_ana id="adana1_1" num="1">
		<ma_ana>aje wani abu.</ma_ana>
		<misali>Ana adana hatsin shuka tun da kaka.</misali>
		<makwatanci lang="far">conserver</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adananne1">
	<kalma>adananne</kalma>
	<furici>àadànánnée</furici>
	<nau_i>k.</nau_i>
	<mace>
		<item>adananna</item>
	</mace>
	<jam_i>
		<item>adanannu</item>
	</jam_i>
	<rukunin_ma_ana id="adananne1_1" num="1">
		<ma_ana>wanda aka adana.</ma_ana>
		<misali>Adanannen goron nan ana iya fiddo shi a raba ma mutane.</misali>
		<makwatanci lang="far">gardé, conservé, protégé</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adano1">
	<kalma>adano</kalma>
	<furici>áadánóo</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="adano1_1" num="1">
		<ma_ana>ajiyar wani abu a wani wuri saboda bukatar yin amfani da shi daga baya.</ma_ana>
		<misali>Zumar da ta samu adano mai kyau, sai a sha ta ko da yaushe.</misali>
		<makwatanci lang="far">action de garder, de conserver</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adar1">
	<kalma>adar</kalma>
	<furici>áadàr</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="adar1_1" num="1">
		<ma_ana>ƙasar adarawa.</ma_ana>
		<misali>Mutamen adar akwai yawon duniya gare su.</misali>
		<makwatanci lang="far">l'Ader</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adashe1">
	<kalma>adashe</kalma>
	<furici>àdàashée</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="adashe1_1" num="1">
		<ma_ana>kuɗi da mutane kaɗan ko da yawa ke tarawa suna ba mutum ɗaya ɗaya har kowa ya ƙwasa.</ma_ana>
		<misali>In mun kwashi adashe sai mu sayi doki.</misali>
		<makwatanci lang="far">tontine</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adawa1">
	<kalma>adawa</kalma>
	<furici>àdáawàa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="adawa1_1" num="1">
		<ma_ana>rishin gamsuwa da wani abu da kuma yin nisa da shi.</ma_ana>
		<misali>Sun gwada adawa da masu gallaza wa talakawa.</misali>
		<makwatanci lang="far">opposition</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adda1">
	<kalma>adda</kalma>
	<furici>àddáa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<jam_i>
		<item>adduna</item>
	</jam_i>
	<rukunin_ma_ana id="adda1_1" num="1">
		<ma_ana>kayan aiki mai kamar takobi, wanda ake iya saran itace da shi.</ma_ana>
		<misali>Ya sare ɗanyen ice da adda.</misali>
		<makwatanci lang="far">coupe-coupe</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="addaba1">
	<kalma>addaba</kalma>
	<furici>àddábàa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<yare>
		<item>haddaba</item>
	</yare>
	<rukunin_ma_ana id="addaba1_1" num="1">
		<ma_ana>halin damuwa wanda ke ga waɗansu.</ma_ana>
		<misali>Sauro addaba ke gare shi.</misali>
		<makwatanci lang="far">action d'emmerder, de déranger</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="addaba2">
	<kalma>addaba</kalma>
	<furici>áddàbáa</furici>
	<nau_i>aik.</nau_i>
	<siffolin_kalma>
		<item>addabe</item>
		<item>addabo</item>
		<item>addabu</item>
	</siffolin_kalma>
	<yare>
		<item>haddaba</item>
	</yare>
	<rukunin_ma_ana id="addaba2_1" num="1">
		<ma_ana>damun mutum ko wani abu.</ma_ana>
		<misali>Ba na son ana addaba ta in ina aiki.</misali>
		<makwatanci lang="far">déranger, emmerder</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="addababbe1">
	<kalma>addababbe</kalma>
	<furici>àddàbábbée</furici>
	<nau_i>k.</nau_i>
	<mace>
		<item>addababba</item>
	</mace>
	<jam_i>
		<item>addababbu</item>
	</jam_i>
	<yare>
		<item>haddababbe</item>
	</yare>
	<rukunin_ma_ana id="addababbe1_1" num="1">
		<ma_ana>wanda ke da halin son damuwar wani.</ma_ana>
		<misali>Wannan yaron addababbe ne, yawan kuka ke gare shi.</misali>
		<makwatanci lang="far">défiant, agaçant, irritant</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="addini1">
	<kalma>addini</kalma>
	<furici>àddíinìi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>addinai</item>
	</jam_i>
	<yare>
		<item>adini</item>
	</yare>
	<rukunin_ma_ana id="addini1_1" num="1">
		<ma_ana>dokoki da farillan bin Ubangiji.</ma_ana>
		<misali>Addini ya koya wa mutane da kar su yi abin da ba ya da kyau.</misali>
		<makwatanci lang="far">religion</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="addu_a1">
	<kalma>addu'a</kalma>
	<furici>àddú'àa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<jam_i>
		<item>addu'o'i</item>
	</jam_i>
	<rukunin_ma_ana id="addu_a1_1" num="1">
		<ma_ana>roƙo na musamman da mutum ke yi zuwa ga Ubangiji.</ma_ana>
		<misali>Kullum in za ka kwanta ka yi addu'a.</misali>
		<makwatanci lang="far">prière</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adiko1">
	<kalma>adiko</kalma>
	<furici>àdíikòo</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>adikuna</item>
	</jam_i>
	<rukunin_ma_ana id="adiko1_1" num="1">
		<ma_ana>a dubi kallabi.</ma_ana>
		<misali>In ta ɗaura adiko sai ka ce ta azo kutuɓu.</misali>
		<makwatanci lang="far">foulard</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="ado1">
	<kalma>ado</kalma>
	<furici>ádóo</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>adodi</item>
		<item>aduduwa</item>
	</jam_i>
	<rukunin_ma_ana id="ado1_1" num="1">
		<ma_ana>kwalliyar da mutum ke yi wa jikinsa ko wani abu, don sa ya yi kyau.</ma_ana>
		<misali>An yi wa ɗakin nan ado mai kyau.</misali>
		<makwatanci lang="far">décoration, ornement, maquillage</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="ado2">
	<kalma>ado</kalma>
	<furici>ádóo</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="ado2_1" num="1">
		<ma_ana>sunan wani ciwo ne mai fiddo ƙuraje ɓulu-ɓulu ga jiki.</ma_ana>
		<misali>Masana sun gano maganin ado.</misali>
		<makwatanci lang="far">varicelle</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="adudu1">
	<kalma>adudu</kalma>
	<furici>àdùdú</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>aduddai</item>
	</jam_i>
	<rukunin_ma_ana id="adudu1_1" num="1">
		<ma_ana>sunan wani ɗan ƙaramin masayi ne, wanda ake yi da haki ko ƴan ƙanƙanan itace ɗanyu da aka gyara.</ma_ana>
		<misali>Ta cika adudu da abubuwa iri-iri.</misali>
		<makwatanci lang="far">petite corbeille en fibre</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="aduwa1">
	<kalma>aduwa</kalma>
	<furici>ádúwàa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<jam_i>
		<item>aduwoyi</item>
	</jam_i>
	<rukunin_ma_ana id="aduwa1_1" num="1">
		<ma_ana>icen Sahara mai doguwar ƙaya, mai ɗiya masu girma kamar kashin raƙumi, suna da ƙaramin ƙodago a cikinsu.</ma_ana>
		<misali>A kasuwar katako ana sayar da ɗiyan aduwa.</misali>
		<makwatanci lang="far">balanitacées</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="afa1">
	<kalma>afa</kalma>
	<furici>áfàa</furici>
	<nau_i>aik.</nau_i>
	<yare>
		<item>afe</item>
	</yare>
	<rukunin_ma_ana id="afa1_1" num="1">
		<ma_ana>jefa gari ko tsakin wani abu cikin baki.</ma_ana>
		<misali>Musa ya afa garin sukari.</misali>
		<makwatanci lang="far">jeter une petite quantité de quelque chose dans la bouche</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="afi1">
	<kalma>afi</kalma>
	<furici>áfìi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="afi1_1" num="1">
		<ma_ana>roƙon gafara tare da watsa ƙasa ga jiki.</ma_ana>
		<misali>A fadar sarki wani kwarto na kuka har da afin ƙasa.</misali>
		<makwatanci lang="far">forme gestuelle de demande de pardon</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="afi2">
	<kalma>afi</kalma>
	<furici>áfìi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="afi2_1" num="1">
		<ma_ana>ɗibar ɗan gari ko tsaba, a jefa baka.</ma_ana>
		<misali>Ya yi afi biyu na gari sai aka kira shi.</misali>
		<makwatanci lang="far">action de jeter une pincée de grains ou de farine, dans la bouche</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="afirilu1">
	<kalma>afirilu</kalma>
	<furici>àfìrílù</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="afirilu1_1" num="1">
		<ma_ana>watan nasara na huɗu ga shekara.</ma_ana>
		<misali>Afirilu wata ne wanda ake zafi a Nijar.</misali>
		<makwatanci lang="far">mois d'avril</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="afuwa1">
	<kalma>afuwa</kalma>
	<furici>áfúwàa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="afuwa1_1" num="1">
		<ma_ana>gafara.</ma_ana>
		<misali>Ɗan da ya yi laifi, ya nemi afuwa.</misali>
		<makwatanci lang="far">pardon, clémence, excuse, amnistie</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agajari1">
	<kalma>agajari</kalma>
	<furici>ágájàaríi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="agajari1_1" num="1">
		<ma_ana>zafin rana wanda ake yi a ƙarshen damana.</ma_ana>
		<misali>Lokacin agajari aiki na da wuya.</misali>
		<makwatanci lang="far">chaleur</makwatanci>
	</rukunin_ma_ana>
	<rukunin_ma_ana id="agajari1_2" num="2">
		<ma_ana>masassara mai kada mutum in zafin ranar kaka ya buga.</ma_ana>
		<misali>Masassarar agajeri ta sake shi.</misali>
		<makwatanci lang="far">fièvre</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agaji1">
	<kalma>agaji</kalma>
	<furici>áagàjíi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="agaji1_1" num="1">
		<ma_ana>taimako.</ma_ana>
		<misali>Ƴan yunwa sun samu agajin abinci.</misali>
		<makwatanci lang="far">aide, secours</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agalemi1">
	<kalma>agalemi</kalma>
	<furici>ágálèemíi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>agalumma</item>
	</jam_i>
	<rukunin_ma_ana id="agalemi1_1" num="1">
		<ma_ana>fatar rago wadda ake yin salla a kanta.</ma_ana>
		<misali>Malam na zaune bisa agalemi yana jan tazbi.</misali>
		<makwatanci lang="far">peau servant à la prière</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agamami1">
	<kalma>agamami</kalma>
	<furici>ágámàamíi</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>agamumma</item>
		<item>agamammai</item>
	</jam_i>
	<rukunin_ma_ana id="agamami1_1" num="1">
		<ma_ana>yaron da aka yi makarar yayewa.</ma_ana>
		<misali>Agamami ba ya bar shan nono ba, amma ya iya hira da kowa.</misali>
		<makwatanci lang="far">enfant tardivement sevré</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agana1">
	<kalma>agana</kalma>
	<furici>ágàanáa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="agana1_1" num="1">
		<ma_ana>wata irin masassara ce.</ma_ana>
		<misali>Agana ta kada shi.</misali>
		<makwatanci lang="far">variole</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agara1">
	<kalma>agara</kalma>
	<furici>ágàráa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<jam_i>
		<item>agarori</item>
	</jam_i>
	<rukunin_ma_ana id="agara1_1" num="1">
		<ma_ana>sunan wata babbar jijiya ce ta bayan ƙafa.</ma_ana>
		<misali>In agara ta ji ciwo, ana jin wuyar tafiya.</misali>
		<makwatanci lang="far">tendon d'Achille</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agarta1">
	<kalma>agarta</kalma>
	<furici>àagártàa</furici>
	<nau_i>s.</nau_i>
	<jinsi>m.</jinsi>
	<rukunin_ma_ana id="agarta1_1" num="1">
		<ma_ana>ƙarfi.</ma_ana>
		<misali>Agartarsa ta isa zuwa yaƙi.</misali>
		<makwatanci lang="far">force</makwatanci>
	</rukunin_ma_ana>
	<rukunin_ma_ana id="agarta1_2" num="2">
		<ma_ana>halin kasancewa balagagge ko mai ƙarfi.</ma_ana>
		<misali>In matashi ya kai ga agarta, ya isa aure kenan.</misali>
		<makwatanci lang="far">action de devenir pubère</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agarta2">
	<kalma>agarta</kalma>
	<furici>áagàrtáa</furici>
	<nau_i>aik.</nau_i>
	<rukunin_ma_ana id="agarta2_1" num="1">
		<ma_ana>zaman mai ƙarfi ko balagagge.</ma_ana>
		<misali>Jakin nan ya agarta.</misali>
		<makwatanci lang="far">devenir fort, devenir pubère</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agartacce1">
	<kalma>agartacce</kalma>
	<furici>ágàrtáccè</furici>
	<nau_i>k.</nau_i>
	<mace>
		<item>agartatta</item>
		<item>agartacciya</item>
	</mace>
	<jam_i>
		<item>agartattu</item>
	</jam_i>
	<rukunin_ma_ana id="agartacce1_1" num="1">
		<ma_ana>wanda ke da ƙarfi.</ma_ana>
		<misali>Wannan sojan agartacce ne.</misali>
		<makwatanci lang="far">fort, puissant</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="a-gashe1">
	<kalma>a-gashe</kalma>
	<furici>àgàshée</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="a-gashe1_1" num="1">
		<ma_ana>a dubi tsire.</ma_ana>
		<misali>Mai gida ya sayo a-gashe wurin barunje.</misali>
		<makwatanci lang="far">brochettes</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agaza1">
	<kalma>agaza</kalma>
	<furici>áagàzáa</furici>
	<nau_i>aik.</nau_i>
	<siffolin_kalma>
		<item>agaje</item>
		<item>agazo</item>
		<item>agazu</item>
	</siffolin_kalma>
	<rukunin_ma_ana id="agaza1_1" num="1">
		<ma_ana>kai taimako zuwa ga wani.</ma_ana>
		<misali>Aikin gonarsa sai da aka agaza masa, ya ƙare.</misali>
		<makwatanci lang="far">aider</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="aggai1">
	<kalma>aggai</kalma>
	<furici>ággài</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="aggai1_1" num="1">
		<ma_ana>barin wuri a koma wani waje.</ma_ana>
		<misali>Da suka yi aggai ba su bar komi ba.</misali>
		<makwatanci lang="far">déménagement</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agigi1">
	<kalma>agigi</kalma>
	<furici>ágígì</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<rukunin_ma_ana id="agigi1_1" num="1">
		<ma_ana>kayan jaki ko raƙumi waɗanda nauyinsu ya zama ɗaya kowace awaza.</ma_ana>
		<misali>Wannan agigi ba ya ɗaukuwa ga jaki, sai raƙumi.</misali>
		<makwatanci lang="far">unités de charge égales transportées par un animal sur chacun de ses flancs</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agogo1">
	<kalma>agogo</kalma>
	<furici>àgóogóo</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<jam_i>
		<item>agoguna</item>
	</jam_i>
	<rukunin_ma_ana id="agogo1_1" num="1">
		<ma_ana>na'urar nasara mai ba da lokaci wadda ake ɗaurawa a hannu.</ma_ana>
		<misali>Agogo ya buga ƙarfe ɗaya.</misali>
		<makwatanci lang="far">montre</makwatanci>
	</rukunin_ma_ana>
</article>

<article id="agola1">
	<kalma>agola</kalma>
	<furici>ágòoláa</furici>
	<nau_i>s.</nau_i>
	<jinsi>n.</jinsi>
	<mace>
		<item>agoliya</item>
	</mace>
	<jam_i>
		<item>agololai</item>
	</jam_i>