<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="application/xml" href="zarma_v7.xsl"?>
<!-- 
Auteurs version papier : projet SouTéBa
Rédacteur en chef : Hamadou Soumana Souna; 
Lexicographes : Hamadou Soumana Souna, Ousseini Soumana, Rakiatou Issoufou, Abdouramane Maidanda
Responsable principal : Thomas Büttner
Coordinateur académique : Mallam Garba Maman

Auteurs version XML : projet DiLAF
Coordinatrice : Chantal Enguehard
Responsable informatique 2010-2016 : Mathieu Mangeot

Publication de référence : Mathieu Mangeot & Chantal Enguehard (2013) Des dictionnaires éditoriaux aux représentations XML standardisées. Chaptre 8, livre "Ressources Lexicales : contenu, construction, utilisation, évaluation", Eds. Nuria Gala & Michael Zock, Linguisticae Investigationes Supplementa, John Benjamins Publishing, Amsterdam, Pays-Bas, 24 p.

Date : 25/07/2017
Version : 1.2
Licence : Creative Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0) : http://creativecommons.org/licenses/by-nc-sa/2.0/
-->

<!DOCTYPE dilaf [
<!ELEMENT dilaf (source, article*)>
<!ATTLIST dilaf src CDATA #REQUIRED>
<!ATTLIST dilaf trg CDATA #REQUIRED>
<!ATTLIST dilaf version CDATA #REQUIRED>
<!ATTLIST dilaf datecreation CDATA #REQUIRED>

<!ELEMENT source (ref*, titre, auteurs, avertissement, license)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (#PCDATA)>
<!ELEMENT avertissement (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license lien CDATA #IMPLIED>

<!ELEMENT article (sanniize, ciiyaŋ*, kanandi?, f*, b*, cidumb*, maana)>
<!ATTLIST article id ID #REQUIRED>

<!ELEMENT maana (feeriji?, silmaŋ*,  himacare*, wayc*, di*,  bareyaŋ?)>
<!ATTLIST maana id ID #REQUIRED>

<!ELEMENT sanniize (#PCDATA)>

<!ELEMENT himacare (#PCDATA)>
<!ATTLIST himacare nufa IDREF #IMPLIED>

<!ELEMENT ciiyaŋ (#PCDATA)>
<!ELEMENT kanandi (#PCDATA)>
<!ELEMENT bareyaŋ (#PCDATA)>
<!ATTLIST bareyaŋ lang (fra) #REQUIRED>

<!ELEMENT feeriji (#PCDATA)>
<!ELEMENT f (#PCDATA)>
<!ELEMENT b (#PCDATA)>

<!ELEMENT di (#PCDATA)>
<!ATTLIST di nufa IDREF #IMPLIED>

<!ELEMENT cidumb (#PCDATA)>
<!ATTLIST cidumb nangu CDATA #IMPLIED>

<!ELEMENT wayc (#PCDATA)>
<!ATTLIST wayc nufa IDREF #IMPLIED>

<!ELEMENT silmaŋ (version+)>
<!ELEMENT version (#PCDATA)>
<!ATTLIST version lang (dje|fra) #REQUIRED>
]>
<dilaf src="dje" trg="fra" version="1.2" datecreation="25/07/2017">
   
   	<source>
		<ref>Soutéba. Dictionnaire zarma-français. Enseignement du cycle de base 1, 2007</ref>
		<titre>Dictionnaire zarma-français.</titre>
		<auteurs>Projet Soutien à l'Education de Base (Soutéba)</auteurs>
		<avertissement>Ce document est protégé par une licence Creative commons Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0). Il est obligatoire d'insérer dans les copies, extraits et versions modifiées de ce fichier le texte suivant : "Ressource issue du dictionnaire dilaf_dje_fra_v1.2.xml hébergée par le site web DiLAF www.dilaf.org. Il est interdit de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier sans faire mention de la même licence ; il est interdit d'utiliser commercialement les informations issues de ce fichier, des copies de ce fichier et des versions modifiées de ce fichier. Il est autorisé de copier ce fichier, de modifier ce fichier, de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier à condition de le faire avec la même licence.</avertissement>
		<license lien="https://creativecommons.org/licenses/by-nc-sa/2.0/">
		</license>
	</source>
	
	<article id="a1">
		<sanniize>a</sanniize>
		<ciiyaŋ>â</ciiyaŋ>
		<kanandi>hantumiize</kanandi>
		<maana id="a1_1">
			<feeriji>zarma ciine abajadaa hantumiize jina ; masida no.</feeriji>
			<bareyaŋ lang="fra">a</bareyaŋ>
		</maana>
	</article>
   
	<article id="a2">
		<sanniize>a</sanniize>
		<ciiyaŋ>à</ciiyaŋ>
		<kanandi>mtub.</kanandi>
		<maana id="a2_1">
			<feeriji>afari boro hinzante ma tubuko.</feeriji>
			<silmaŋ>
				<version lang="dje">Ali koy habu amma a mana kande habiize.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">il, elle, le, la, l'</bareyaŋ>
		</maana>
	</article>
   
	<article id="a3">
		<sanniize>a</sanniize>
		<ciiyaŋ>à</ciiyaŋ>
		<kanandi>wsif.</kanandi>
		<maana id="a3_1">
			<feeriji>afari boro hinzante wanetaray tubuko.</feeriji>
			<silmaŋ>
				<version lang="dje">Muusa to ga fatta no a cora ka ga a hã.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">son, sa, ses</bareyaŋ>
		</maana>
	</article>
   
	<article id="a4">
		<sanniize>a</sanniize>
		<ciiyaŋ>á</ciiyaŋ>
		<kanandi>mtub.</kanandi>
		<maana id="a4_1">
			<feeriji>afari boro si tubuko.</feeriji>
			<silmaŋ>
				<version lang="dje">A si boori zanka ma albeeri wow.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">on</bareyaŋ>
		</maana>
	</article>
   
	<article id="a5">
		<sanniize>a</sanniize>
		<ciiyaŋ>ǎa</ciiyaŋ>
		<kanandi>tuuy.</kanandi>
		<maana id="a5_1">
			<feeriji>sanniize no kaŋ boro ga ci ga tu ceeyaŋ se.</feeriji>
			<silmaŋ>
				<version lang="dje">A ! Ni no go ga ay ce Tondi ?</version>
			</silmaŋ>
			<himacare nufa="naam1">naam</himacare>
			<bareyaŋ lang="fra">oui</bareyaŋ>
		</maana>
	</article>
   
	<article id="a_a1">
		<sanniize>a'a</sanniize>
		<ciiyaŋ>áà</ciiyaŋ>
		<kanandi>tuuy.</kanandi>
		<maana id="a_a1_1">
			<feeriji>sanniize no kaŋ i ga ci ga wanjay cabe wala ga sanni fo ka.</feeriji>
			<silmaŋ>
				<version lang="dje">A'a, ni si koy iri bande.</version>
			</silmaŋ>
			<himacare nufa="abada1">abada</himacare>
			<himacare nufa="hã_ã1">hã'ã</himacare>
			<bareyaŋ lang="fra">non</bareyaŋ>
		</maana>
	</article>
   
	<article id="abaara1">
		<sanniize>abaara</sanniize>
		<ciiyaŋ>ábâarà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>abaaraa</f>
		<b>abaarey</b>
		<maana id="abaara1_1">
			<feeriji>hari hi bambata no.</feeriji>
			<silmaŋ>
				<version lang="dje">Abaara ra no yaawarancey ga naaru.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">grande pirogue</bareyaŋ>
		</maana>
	</article>
   
	<article id="abada1">
		<sanniize>abada</sanniize>
		<ciiyaŋ>ábádǎa</ciiyaŋ>
		<kanandi>tuuy.</kanandi>
		<maana id="abada1_1">
			<feeriji>sanniize no kaŋ boro ga tu nda hããyaŋ se ga cabe kaŋ manti ya-din no.</feeriji>
			<silmaŋ>
				<version lang="dje">Abada, almaney mana koy kuray.</version>
			</silmaŋ>
			<himacare nufa="hã_ã1">hã'ã</himacare>
			<himacare>habada</himacare>
			<bareyaŋ lang="fra">non</bareyaŋ>
		</maana>
	</article>
   
	<article id="abada2">
		<sanniize>abada</sanniize>
		<ciiyaŋ>àbàdá</ciiyaŋ>
		<kanandi>teeb.</kanandi>
		<maana id="abada2_1">
			<feeriji>ba ce fo.</feeriji>
			<silmaŋ>
				<version lang="dje">Boro mana hima ga hayra kayna, abada.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">jamais</bareyaŋ>
		</maana>
	</article>
   
	<article id="abada3">
		<sanniize>abada</sanniize>
		<ciiyaŋ>àbàdá</ciiyaŋ>
		<kanandi>teeb.</kanandi>
		<maana id="abada3_1">
			<feeriji>waati kulu.</feeriji>
			<silmaŋ>
				<version lang="dje">Da boro ga naaru boro katto ma bara boro ga, abada.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">toujours</bareyaŋ>
		</maana>
	</article>
   
	<article id="abajada1">
		<sanniize>abajada</sanniize>
		<ciiyaŋ>ábàjádà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>abajadaa</f>
		<b>abajadey</b>
		<maana id="abajada1_1">
			<feeriji>hantumiizey kulu marganta kaŋ i ga ciine fo hantum nda.</feeriji>
			<silmaŋ>
				<version lang="dje">Zarma ciine abajadaa sinda kala hantumiize waranza.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">alphabet</bareyaŋ>
		</maana>
	</article>
   
	<article id="abalkada1">
		<sanniize>abalkada</sanniize>
		<ciiyaŋ>ábàlkádà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>abalkadaa</f>
		<b>abalkadey</b>
		<maana id="abalkada1_1">
			<feeriji>fuula deene cuttikoy kaŋ gonda hanga alhaali yaŋ.</feeriji>
			<silmaŋ>
				<version lang="dje">Doŋ wangaarey, gawey nda kurkey no ga ba abalkada daŋyaŋ.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">bonnet traditionnel qui couvre les oreilles</bareyaŋ>
		</maana>
	</article>
   
	<article id="abarba1">
		<sanniize>abarba</sanniize>
		<ciiyaŋ>ábàrbà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>abarbaa</f>
		<b>abarbey</b>
		<maana id="abarba1_1">
			<feeriji>banaana dumi no kaŋ i ga haagu ga ŋwa.</feeriji>
			<silmaŋ>
				<version lang="dje">Muusa na abarba kilo day ga kande nga zankey se.</version>
			</silmaŋ>
			<himacare nufa="budde1">budde</himacare>
			<bareyaŋ lang="fra">type de banane</bareyaŋ>
		</maana>
	</article>
   
	<article id="abirillu1">
		<sanniize>abirillu</sanniize>
		<ciiyaŋ>àbìríllù</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>abirillo</f>
		<b>abirilley</b>
		<maana id="abirillu1_1">
			<feeriji>annasaara handu taacanta kaŋ go marsu nda me game ra.</feeriji>
			<silmaŋ>
				<version lang="dje">Abirillu hando ra dungay no ga te gumo.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">avril</bareyaŋ>
		</maana>
	</article>
   
	<article id="abiyanso1">
		<sanniize>abiyanso</sanniize>
		<ciiyaŋ>àbìyànsôo</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>abiyansa</f>
		<b>abiyansey</b>
		<maana id="abiyanso1_1">
			<feeriji>batama kaŋ ra abiyey ga zumbu.</feeriji>
			<silmaŋ>
				<version lang="dje">Tilbeeri nda Dooso sinda abiyanso kaŋ ra abiyo beeri ga zumbu.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">aéroport</bareyaŋ>
		</maana>
	</article>
   
	<article id="abiyo1">
		<sanniize>abiyo</sanniize>
		<ciiyaŋ>àbíyò</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>abiya</f>
		<b>abiyey</b>
		<maana id="abiyo1_1">
			<feeriji>naarumay hari no kaŋ ra i ga boro nda jinay daŋ a ma deesi nd'ey.</feeriji>
			<silmaŋ>
				<version lang="dje">Sohon abiyo ra no borey ga koy Makka.</version>
			</silmaŋ>
			<himacare nufa="beene-hi1">beene-hi</himacare>
			<bareyaŋ lang="fra">avion</bareyaŋ>
		</maana>
	</article>
   
	<article id="abunaadam1">
		<sanniize>abunaadam</sanniize>
		<ciiyaŋ>àbúnǎadàm</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>abunaadamo</f>
		<b>abunaadamey</b>
		<maana id="abunaadam1_1">
			<di nufa="adamayze1">adamayze</di>
			<bareyaŋ lang="fra">être humain, personne</bareyaŋ>
		</maana>
	</article>
   
	<article id="adaase1">
		<sanniize>adaase</sanniize>
		<ciiyaŋ>àdàasé</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adaasa</f>
		<b>adaasey</b>
		<maana id="adaase1_1">
			<feeriji>nooru marguyaŋ kaŋ jama ga te waafakay ra, i ga a ku ga dake care ga, alwaati ga ka alwaati.</feeriji>
			<silmaŋ>
				<version lang="dje">Adaase no Maymuna ku ga sintin ga fatawci.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">tontine</bareyaŋ>
		</maana>
	</article>
   
	<article id="adaase-ɲa1">
		<sanniize>adaase-ɲa</sanniize>
		<ciiyaŋ>àdaàsé-ɲà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adaase-ɲaŋo</f>
		<b>adaase-ɲaŋey</b>
		<maana id="adaase-ɲa1_1">
			<feeriji>bora kaŋ ga adaase nooru margu.</feeriji>
			<silmaŋ>
				<version lang="dje">Boro kulu kaŋ ku adaase no ga adaase-ɲa no gooro.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">collecteur (de tontine)</bareyaŋ>
		</maana>
	</article>
   
	<article id="adaawa1">
		<sanniize>adaawa</sanniize>
		<ciiyaŋ>àdàawá</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adaawaa</f>
		<maana id="adaawa1_1">
			<himacare nufa="hasaraw2">hasaraw</himacare>
			<himacare nufa="masiiba1">masiiba</himacare>
			<himacare nufa="mulsay2">mulsay</himacare>
			<himacare nufa="balaawu1">balaawu</himacare>
			<di nufa="bone1">bone</di>
			<bareyaŋ lang="fra">catastrophe, malheur</bareyaŋ>
		</maana>
	</article>
   
	<article id="adadi1">
		<sanniize>adadi</sanniize>
		<ciiyaŋ>àdádì</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adado</f>
		<b>adadey</b>
		<maana id="adadi1_1">
			<feeriji>boro wala hari fo hina.</feeriji>
			<silmaŋ>
				<version lang="dje">Neerandikey mana hima ga zabu neesijo adado ga.</version>
			</silmaŋ>
			<himacare>haddi</himacare>
			<himacare nufa="hadadi1">hadadi</himacare>
			<bareyaŋ lang="fra">capacité, contenu, possibilité, pouvoir</bareyaŋ>
		</maana>
	</article>
   
	<article id="adaka1">
		<sanniize>adaka</sanniize>
		<ciiyaŋ>àdákà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adakaa</f>
		<b>adakey</b>
		<maana id="adaka1_1">
			<feeriji>jinay kaŋ i ga te nda bundu wala guuru ga bankaaray wala jinay fo yaŋ daŋ ga gisi, i ma hallasi.</feeriji>
			<silmaŋ>
				<version lang="dje">Kurmiizo kande adaka me fo jinay.</version>
			</silmaŋ>
			<himacare nufa="sundurku1">sundurku</himacare>
			<bareyaŋ lang="fra">caisse, valise, malle</bareyaŋ>
		</maana>
	</article>
   
	<article id="adamayze1">
		<sanniize>adamayze</sanniize>
		<ciiyaŋ>ádàmǎyzè</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adamayzo</f>
		<b>adamayzey</b>
		<maana id="adamayze1_1">
			<feeriji>annabi Adamu banda.</feeriji>
			<silmaŋ>
				<version lang="dje">Adamayze kaŋ si goy nda nga lakkalo mana waana alman.</version>
			</silmaŋ>
			<himacare nufa="boro1">boro</himacare>
			<himacare nufa="munaadam1">munaadam</himacare>
			<himacare nufa="munaadamiize1">munaadamiize</himacare>
			<himacare nufa="andamiize1">andamiize</himacare>
			<himacare nufa="abunaadam1">abunaadam</himacare>
			<himacare nufa="inaadamiize1">inaadamiize</himacare>
			<bareyaŋ lang="fra">humain, homme, personne</bareyaŋ>
		</maana>
	</article>
   
	<article id="adamayzetaray1">
		<sanniize>adamayzetaray</sanniize>
		<ciiyaŋ>àdàmàyzètàrây</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adamayzetara</f>
		<maana id="adamayzetaray1_1">
			<feeriji>alhaali hanno kaŋ boro ga cabe.</feeriji>
			<silmaŋ>
				<version lang="dje">Caana ga alfukaaru konzo, a gonda adamayzetaray.</version>
			</silmaŋ>
			<himacare>munaadamiizetaray</himacare>
			<bareyaŋ lang="fra">humanisme, gentillesse, sympathie</bareyaŋ>
		</maana>
	</article>
   
	<article id="adani1">
		<sanniize>adani</sanniize>
		<ciiyaŋ>àdànîi</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adaniyo</f>
		<b>adaniyey</b>
		<maana id="adani1_1">
			<feeriji>boro kaŋ boŋo bu, kaŋ sinda fahamay.</feeriji>
			<silmaŋ>
				<version lang="dje">Adani si waani borey ra goray.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">idiot, cancre, sot, con</bareyaŋ>
		</maana>
	</article>
   
	<article id="adani2">
		<sanniize>adani</sanniize>
		<ciiyaŋ>àdànîi</ciiyaŋ>
		<kanandi>tsif.</kanandi>
		<f>adaniyo</f>
		<b>adaniyey</b>
		<maana id="adani2_1">
			<feeriji>sifa no kaŋ i ga te boro kaŋ boŋo bu, a si hari fo bay, a teerey mo sinda maana se.</feeriji>
			<silmaŋ>
				<version lang="dje">Zanka adani si faham hari kaŋ cawandika ga ci a se.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">idiot, cancre, sot, con</bareyaŋ>
		</maana>
	</article>
   
	<article id="adanitaray1">
		<sanniize>adanitaray</sanniize>
		<ciiyaŋ>àdànìtàrây</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adanitara</f>
		<maana id="adanitaray1_1">
			<feeriji>haalo kaŋ go adani ga.</feeriji>
			<silmaŋ>
				<version lang="dje">Koociyo adanitara laala, a si hin ga kabu ga to ba iway.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">idiotie, sottise, connerie</bareyaŋ>
		</maana>
	</article>
   
	<article id="adar1">
		<sanniize>adar</sanniize>
		<ciiyaŋ>ádàr</ciiyaŋ>
		<kanandi>m.</kanandi>
		<maana id="adar1_1">
			<feeriji>ma no kaŋ i ga Taawa laabu ce nda.</feeriji>
			<silmaŋ>
				<version lang="dje">Kadade wo Ader argurjay no kaŋ te ma gumo.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">Ader</bareyaŋ>
		</maana>
	</article>
   
	<article id="adarance1">
		<sanniize>adarance</sanniize>
		<ciiyaŋ>àdàràncé</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adaranca</f>
		<b>adarancey</b>
		<maana id="adarance1_1">
			<feeriji>adar boro.</feeriji>
			<silmaŋ>
				<version lang="dje">Adarance ga waani fatawci.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">aderawa, habitant de l'Ader</bareyaŋ>
		</maana>
	</article>
   
	<article id="adda1">
		<sanniize>adda</sanniize>
		<ciiyaŋ>àddá</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>addaa</f>
		<b>addey</b>
		<maana id="adda1_1">
			<feeriji>guuru tafay no kaŋ gonda bundu wala donko boŋ ; i ga zafa nd'a, i ga guusu fansi nd'a.</feeriji>
			<silmaŋ>
				<version lang="dje">Adda me kaanokoy zafayaŋ ga kaanu.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">machette, coupe-coupe</bareyaŋ>
		</maana>
	</article>
   
	<article id="addaabu1">
		<sanniize>addaabu</sanniize>
		<ciiyaŋ>áddáabú</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>addaabo</f>
		<b>addaabey</b>
		<maana id="addaabu1_1">
			<feeriji>zaara kaŋ i ga daabu nd’a.</feeriji>
			<silmaŋ>
				<version lang="dje">Za jawo to no i ga day zankey se addaabu.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">couverture (pour se protéger contre le froid)</bareyaŋ>
		</maana>
	</article>
   
	<article id="addiini1">
		<sanniize>addiini</sanniize>
		<ciiyaŋ>àddíinì</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>addiino</f>
		<b>addiiney</b>
		<maana id="addiini1_1">
			<di nufa="diina1">diina</di>
			<bareyaŋ lang="fra">religion</bareyaŋ>
		</maana>
	</article>
   
	<article id="adduha1">
		<sanniize>adduha</sanniize>
		<ciiyaŋ>àddùhâa</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adduhaa</f>
		<b>adduhey</b>
		<cidumb>aduha</cidumb>
		<cidumb>aduwa</cidumb>
		<maana id="adduha1_1">
			<feeriji>alwaati kaŋ wayna ga sintin ga koroŋ.</feeriji>
			<silmaŋ>
				<version lang="dje">Adduha ra no wayborey ga koy habu ga foy-jinay day.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">moment compris entre neuf heures et dix heures</bareyaŋ>
		</maana>
	</article>
   
	<article id="adduha2">
		<sanniize>adduha</sanniize>
		<ciiyaŋ>àddùhâa</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adduhaa</f>
		<b>adduhey</b>
		<cidumb>aduha</cidumb>
		<cidumb>aduwa</cidumb>
		<maana id="adduha2_1">
			<feeriji>jingaro kaŋ alsilaamey ga te alwaato kaŋ wayna ga sintin ga koroŋ.</feeriji>
			<silmaŋ>
				<version lang="dje">Alsilaamo kaŋ na diinaa di nda gaabi no ga adduha jingar.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">prière (de fin de matinée)</bareyaŋ>
		</maana>
	</article>
   
	<article id="adduwa1">
		<sanniize>adduwa</sanniize>
		<ciiyaŋ>àddúwà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adduwaa</f>
		<b>adduwey</b>
		<maana id="adduwa1_1">
			<feeriji>Irkoy-ŋwaaray.</feeriji>
			<silmaŋ>
				<version lang="dje">Iri adduwaa kaanu, beena haro kaŋ.</version>
			</silmaŋ>
			<himacare nufa="faatiya2">faatiya</himacare>
			<himacare nufa="duwaawu1">duwaawu</himacare>
			<himacare nufa="ŋwaaray5">ŋwaaray</himacare>
			<bareyaŋ lang="fra">prière, invocation divine</bareyaŋ>
		</maana>
	</article>
   
	<article id="adduwa2">
		<sanniize>adduwa</sanniize>
		<ciiyaŋ>àddúwà</ciiyaŋ>
		<kanandi>teerks.</kanandi>
		<maana id="adduwa2_1">
			<feeriji>boro ma Irkoy ŋwaaray.</feeriji>
			<silmaŋ>
				<version lang="dje">Za alsilaamey jingar ga ban no i ga adduwa.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">prier, invoquer Dieu</bareyaŋ>
		</maana>
	</article>
   
	<article id="adiika1">
		<sanniize>adiika</sanniize>
		<ciiyaŋ>àdíikà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adiikaa</f>
		<b>adiikey</b>
		<maana id="adiika1_1">
			<feeriji>zaara wala mosooro kaŋ ra i na jinay daŋ ga haw.</feeriji>
			<silmaŋ>
				<version lang="dje">Abdu na nga bankaarey kulu daŋ adiika ra ga koto.</version>
			</silmaŋ>
			<himacare nufa="diiku1">diiku</himacare>
			<bareyaŋ lang="fra">baluchon, ballot</bareyaŋ>
		</maana>
	</article>
   
	<article id="adiina1">
		<sanniize>adiina</sanniize>
		<ciiyaŋ>àdíinà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adiinaa</f>
		<b>adiiney</b>
		<maana id="adiina1_1">
			<di nufa="diina1">diina</di>
			<bareyaŋ lang="fra">religion</bareyaŋ>
		</maana>
	</article>
   
	<article id="adilante1">
		<sanniize>adilante</sanniize>
		<ciiyaŋ>àdìlànté</ciiyaŋ>
		<kanandi>tsif.</kanandi>
		<f>adilanta</f>
		<b>adilantey</b>
		<maana id="adilante1_1">
			<feeriji>sifa no kaŋ i ga te boro kaŋ gonda amaana se.</feeriji>
			<silmaŋ>
				<version lang="dje">Alkaali adilante gonda darza borey do.</version>
			</silmaŋ>
			<himacare nufa="adili2">adili</himacare>
			<bareyaŋ lang="fra">honnête, loyal, confident, sincère</bareyaŋ>
		</maana>
	</article>
   
	<article id="adilay1">
		<sanniize>adilay</sanniize>
		<ciiyaŋ>ádíláy</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adila</f>
		<maana id="adilay1_1">
			<feeriji>amaana gaayiyaŋ.</feeriji>
			<silmaŋ>
				<version lang="dje">Jine-borey hima ga adilay daŋ ngey goyey ra.</version>
			</silmaŋ>
			<himacare nufa="adilitaray1">adilitaray</himacare>
			<bareyaŋ lang="fra">loyauté, sincérité, honnêteté, impartialité</bareyaŋ>
		</maana>
	</article>
   
	<article id="adilay2">
		<sanniize>adilay</sanniize>
		<ciiyaŋ>ádíláy</ciiyaŋ>
		<kanandi>teerks.</kanandi>
		<maana id="adilay2_1">
			<feeriji>boro ma ciiti nda fondo boro yaŋ game.</feeriji>
			<silmaŋ>
				<version lang="dje">Zuuzey hima ga adilay ciiti dumbuyaŋ ga.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">être honnête, être loyal, inspirer confiance, être sincère</bareyaŋ>
		</maana>
	</article>
   
	<article id="adili1">
		<sanniize>adili</sanniize>
		<ciiyaŋ>ádílì</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adilo</f>
		<b>adiley</b>
		<maana id="adili1_1">
			<feeriji>boro kaŋ gonda naanay, kaŋ si amaana ŋwa.</feeriji>
			<silmaŋ>
				<version lang="dje">Da boro na jinay talfi adili ga, boro ma si joote.</version>
			</silmaŋ>
			<himacare nufa="hayyaŋiize1">hayyaŋiize</himacare>
			<himacare nufa="adilante1">adilante</himacare>
			<bareyaŋ lang="fra">honnête, confident, sincère, juste, loyal</bareyaŋ>
		</maana>
	</article>
   
	<article id="adili2">
		<sanniize>adili</sanniize>
		<ciiyaŋ>ádílì</ciiyaŋ>
		<kanandi>tsif.</kanandi>
		<f>adilo</f>
		<b>adiley</b>
		<maana id="adili2_1">
			<feeriji>sifa no kaŋ i ga te boro kaŋ gonda amaana se.</feeriji>
			<silmaŋ>
				<version lang="dje">Bonkooni adili gonda darza talkey do.</version>
			</silmaŋ>
			<himacare nufa="adilante1">adilante</himacare>
			<bareyaŋ lang="fra">honnête, loyal, confident, sincère, juste</bareyaŋ>
		</maana>
	</article>
   
	<article id="adilitaray1">
		<sanniize>adilitaray</sanniize>
		<ciiyaŋ>àdìlìtàrây</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adilitara</f>
		<maana id="adilitaray1_1">
			<feeriji>amaana gaayiyaŋ.</feeriji>
			<silmaŋ>
				<version lang="dje">Adilitaray ga boori.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">honnêteté, loyauté, sincérité</bareyaŋ>
		</maana>
	</article>
   
	<article id="adookaafile1">
		<sanniize>adookaafile</sanniize>
		<ciiyaŋ>àdòokàafílé</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>adookaafila</f>
		<b>adookaafiley</b>
		<maana id="adookaafile1_1">
			<di nufa="dookaafile1">dookaafile</di>
			<bareyaŋ lang="fra">friperie</bareyaŋ>
		</maana>
	</article>
   
	<article id="afirki1">
		<sanniize>afirki</sanniize>
		<ciiyaŋ>áfǐrkì</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>afirko</f>
		<maana id="afirki1_1">
			<feeriji>Boro-bi laabey fando.</feeriji>
			<silmaŋ>
				<version lang="dje">Afirki fando borey baayaŋo kulu boro-bi yaŋ no.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">Afrique</bareyaŋ>
		</maana>
	</article>
   
	<article id="afo1">
		<sanniize>afo</sanniize>
		<ciiyaŋ>àfó</ciiyaŋ>
		<kanandi>kab.</kanandi>
		<f>afa</f>
		<b>afey</b>
		<maana id="afo1_1">
			<feeriji>zarma ciine kabiize sintina.</feeriji>
			<silmaŋ>
				<version lang="dje">251 ra afo wo kabiize no.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">unité</bareyaŋ>
		</maana>
	</article>
   
	<article id="afo2">
		<sanniize>afo</sanniize>
		<ciiyaŋ>àfó</ciiyaŋ>
		<kanandi>dsif.</kanandi>
		<maana id="afo2_1">
			<feeriji>kaŋ manti jare, a mana to mo ihinka.</feeriji>
			<silmaŋ>
				<version lang="dje">Feejey kaŋ koy kuray ra afo mana jaaje.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">un, une</bareyaŋ>
		</maana>
	</article>
   
	<article id="afo3">
		<sanniize>afo</sanniize>
		<ciiyaŋ>àfó</ciiyaŋ>
		<kanandi>mtub.</kanandi>
		<f>afa</f>
		<b>afey</b>
		<maana id="afo3_1">
			<feeriji>boro, alman wala hari kaŋ sanni i go ga te.</feeriji>
			<silmaŋ>
				<version lang="dje">Ma si donda afa kaŋ ni di, a ga wasa borey kulu se.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">celui, celle</bareyaŋ>
		</maana>
	</article>
   
	<article id="afolloŋ1">
		<sanniize>afolloŋ</sanniize>
		<ciiyaŋ>àfóllóŋ</ciiyaŋ>
		<kanandi>dsif.</kanandi>
		<maana id="afolloŋ1_1">
			<feeriji>afo hinne.</feeriji>
			<silmaŋ>
				<version lang="dje">Lokkoliizey kaŋ koy yoona do ra, afolloŋ no mana du.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">un (e) seul (e)</bareyaŋ>
		</maana>
	</article>
   
	<article id="agaram1">
		<sanniize>agaram</sanniize>
		<ciiyaŋ>àgàrâm</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>agaramo</f>
		<b>agaramey</b>
		<maana id="agaram1_1">
			<feeriji>caaca no kaŋ ra i ga boro kulu no kattayze gu.</feeriji>
			<silmaŋ>
				<version lang="dje">Waato din, agaram no caacayzey ga kar nda baayaŋ.</version>
			</silmaŋ>
			<himacare nufa="algaram1">algaram</himacare>
			<bareyaŋ lang="fra">type de jeu de cartes</bareyaŋ>
		</maana>
	</article>
   
	<article id="agargar1">
		<sanniize>agargar</sanniize>
		<ciiyaŋ>ágárgàr</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>agargaro</f>
		<b>agargarey</b>
		<maana id="agargar1_1">
			<feeriji>tuuriize no kaŋ ga hima kalhã, a ga boro gunda kar da boro na a haŋ.</feeriji>
			<silmaŋ>
				<version lang="dje">Argagar ga boro wi, da boro na a haŋ ga laala.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">acacia italica</bareyaŋ>
		</maana>
	</article>
   
	<article id="agusi1">
		<sanniize>agusi</sanniize>
		<ciiyaŋ>àgúsí</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>aguso</f>
		<b>agusey</b>
		<maana id="agusi1_1">
			<feeriji>labtanda fo dumi izo wane baalo.</feeriji>
			<silmaŋ>
				<version lang="dje">Yaawo na agusi duru ga daŋ nga foyo ra ga a komandi.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">grain semblable à la graine de courge utilisé comme condiment</bareyaŋ>
		</maana>
	</article>
   
	<article id="agwaala1">
		<sanniize>agwaala</sanniize>
		<ciiyaŋ>àgwàalà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>agwaalaa</f>
		<b>agwaaley</b>
		<maana id="agwaala1_1">
			<feeriji>malfa beeri no kaŋ ra i ga arsaniize bambata daŋ ga kar.</feeriji>
			<silmaŋ>
				<version lang="dje">Agwaala no soojey ga care kar nda, wangu ra.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">canon</bareyaŋ>
		</maana>
	</article>
   
	<article id="ahã1">
		<sanniize>ahã</sanniize>
		<ciiyaŋ>áhã</ciiyaŋ>
		<kanandi>damb.</kanandi>
		<maana id="ahã1_1">
			<feeriji>sanniize no kaŋ boro ga ci ga cabe kaŋ haro na boro dambarandi.</feeriji>
			<silmaŋ>
				<version lang="dje">Ahã, ni no na kalaaso ziibandi !</version>
			</silmaŋ>
			<bareyaŋ lang="fra">ah bon !</bareyaŋ>
		</maana>
	</article>
   
	<article id="ahã2">
		<sanniize>ahã</sanniize>
		<ciiyaŋ>àhã</ciiyaŋ>
		<kanandi>tuuy.</kanandi>
		<maana id="ahã2_1">
			<feeriji>sanniize no kaŋ boro ga ci ga cabe kaŋ boro yadda.</feeriji>
			<silmaŋ>
				<version lang="dje">Ahã, ay ta sanno kaŋ ni ci.</version>
			</silmaŋ>
			<himacare nufa="to3">to</himacare>
			<bareyaŋ lang="fra">d'accord, c'est ça, oui</bareyaŋ>
		</maana>
	</article>
   
	<article id="ahakkante1">
		<sanniize>ahakkante</sanniize>
		<ciiyaŋ>áhàkkànté</ciiyaŋ>
		<kanandi>bsif.</kanandi>
		<f>ahakkanta</f>
		<b>ahankatey</b>
		<maana id="ahakkante1_1">
			<feeriji>gurbi no kaŋ go iyyanta nda yagganta game ra.</feeriji>
			<silmaŋ>
				<version lang="dje">Boro ahakkante Ali no ka yoona ga.</version>
			</silmaŋ>
			<himacare nufa="hakkante1">hakkante</himacare>
			<bareyaŋ lang="fra">huitième</bareyaŋ>
		</maana>
	</article>
   
	<article id="ahakku1">
		<sanniize>ahakku</sanniize>
		<ciiyaŋ>àhákkù</ciiyaŋ>
		<kanandi>dsif.</kanandi>
		<f>ahakko</f>
		<b>ahakkey</b>
		<maana id="ahakku1_1">
			<feeriji>kabiizo kaŋ ga ka iyye banda.</feeriji>
			<silmaŋ>
				<version lang="dje">Ihinka-hinka taaci no ga te ahakku.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">huit</bareyaŋ>
		</maana>
	</article>
   
	<article id="akanka1">
		<sanniize>akanka</sanniize>
		<ciiyaŋ>àkánkà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>akankaa</f>
		<b>akankey</b>
		<maana id="akanka1_1">
			<feeriji>kumbu-boŋ.</feeriji>
			<silmaŋ>
				<version lang="dje">Kumbu kaŋ sinda akanka farmi si kaanu.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">manche de hilaire</bareyaŋ>
		</maana>
	</article>
   
	<article id="akiika1">
		<sanniize>akiika</sanniize>
		<ciiyaŋ>àkíikà</ciiyaŋ>
		<kanandi>tuuy.</kanandi>
		<maana id="akiika1_1">
			<feeriji>sanniize no kaŋ ga hari fo tabbatandi.</feeriji>
			<silmaŋ>
				<version lang="dje">Akiika, suba ay ga koy habu.</version>
			</silmaŋ>
			<himacare nufa="hakiika1">hakiika</himacare>
			<bareyaŋ lang="fra">exact, effectivement, c'est ça, oui, vrai</bareyaŋ>
		</maana>
	</article>
   
	<article id="akiika2">
		<sanniize>akiika</sanniize>
		<ciiyaŋ>àkíikà</ciiyaŋ>
		<kanandi>m.</kanandi>
		<maana id="akiika2_1">
			<feeriji>sanniize no kaŋ ga hari fo tabbatandi.</feeriji>
			<silmaŋ>
				<version lang="dje">Ay sinda sanno din akiikaa.</version>
			</silmaŋ>
			<himacare nufa="hakiika1">hakiika</himacare>
			<bareyaŋ lang="fra">exactitude, assurance</bareyaŋ>
		</maana>
	</article>
   
	<article id="aku1">
		<sanniize>aku</sanniize>
		<ciiyaŋ>àkú</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>Akuwo</f>
		<b>akuwey</b>
		<maana id="aku1_1">
			<feeriji>curayze no kaŋ i ga biiri, a ga hin ga boro sanni dondon.</feeriji>
			<silmaŋ>
				<version lang="dje">Annasaarey no ga aku day ga gaayi ngey fuwey ra.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">perroquet</bareyaŋ>
		</maana>
	</article>
   
	<article id="akusi1">
		<sanniize>akusi</sanniize>
		<ciiyaŋ>àkúsí</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>akuso</f>
		<b>akusey</b>
		<maana id="akusi1_1">
			<feeriji>caŋ no kaŋ ga to tobay beeray ; borey ga a hamo ŋwa.</feeriji>
			<silmaŋ>
				<version lang="dje">Bi-fo koliyo hane, borey na akusi boobo wi.</version>
			</silmaŋ>
			<bareyaŋ lang="fra">rat géant</bareyaŋ>
		</maana>
	</article>
   
	<article id="akwaaku1">
		<sanniize>akwaaku</sanniize>
		<ciiyaŋ>àkwáakú</ciiyaŋ>
		<kanandi>m.</kanandi>
		<f>akwaako</f>
		<b>akwaakey</b>
		<maana id="akwaaku1_1">
			<feeriji>teeburiize no kaŋ boŋ i ga jinay buuno-buuno dake ga talle kwaaraa ra.</feeriji>
			<silmaŋ>
				<version lang="dje">Akwaaku ra no Abdu ga nga jiney neera kwaaraa ra.</version>
			</silmaŋ>