<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="application/xml" href="kanouri_v4.xsl"?>
<!-- 
Auteurs version papier : projet SouTéBa
Rédacteur en chef : Abdoulkarim Chérif Ari
Lexicographes : Abdoulkarim Chérif Ari, Arimi Boukar, Jarrett Kevin Anthon, Maï Moussa Maï, Manoua Djibir, Mme Taweye Aichéta Chégou Kore
Responsable principal : Thomas Büttner
Coordinateur académique : Mallam Garba Maman

Auteurs version XML : projet DiLAF
Coordinatrice : Chantal Enguehard
Responsable informatique 2010-2016 : Mathieu Mangeot

Publication de référence : Mathieu Mangeot & Chantal Enguehard (2013) Des dictionnaires éditoriaux aux représentations XML standardisées. Chaptre 8, livre "Ressources Lexicales : contenu, construction, utilisation, évaluation", Eds. Nuria Gala & Michael Zock, Linguisticae Investigationes Supplementa, John Benjamins Publishing, Amsterdam, Pays-Bas, 24 p.

Date : 25/07/2017
Version : 1.3
Licence : Creative Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0) : http://creativecommons.org/licenses/by-nc-sa/2.0/

____ Début partie à ôter dans version diffusée ____
31/01/2016 : correction du français (typo, etc.)
				<maana> majuscule initiale, point final
				<version tǝlam="ka"> majuscule initiale, point final
				<kalakta tǝlam="fa"> minuscule initiale, pas de point final
25/07/2017 : suppression des attributs (cible) kandan2, kandan3, kandan4.
				
A Faire
	ôter attributs 'verifier' dans articles et DTD	
			"]+""
	ôter éléments flore dans articles et DTD
	
	
____ Fin partie à ôter dans version diffusée ____

-->
<!DOCTYPE dilaf [
<!ELEMENT dilaf (source, article*)>
<!ATTLIST dilaf src CDATA #REQUIRED>
<!ATTLIST dilaf trg CDATA #REQUIRED>
<!ATTLIST dilaf version CDATA #REQUIRED>
<!ATTLIST dilaf datecreation CDATA #REQUIRED>

<!ELEMENT source (ref*, titre, auteurs, avertissement, license)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (#PCDATA)>
<!ELEMENT avertissement (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license lien CDATA #IMPLIED>

<!ELEMENT article (kalma, bowodu?, bowodu_gade*, naptu_curo_nahauyen, kǝnyakkuye_tilola?, ngǝwula?, bǝri)>
<!ATTLIST article id ID #REQUIRED>

<!ELEMENT bǝri (maana?,  misal*, mane*, maana_tiloa*, fǝrǝm*, kalakta?)>
<!ATTLIST bǝri id ID #REQUIRED>

<!ELEMENT kalma (#PCDATA)>
<!ELEMENT bowodu (#PCDATA)>
<!ELEMENT naptu_curo_nahauyen (#PCDATA)>
<!ELEMENT maana (#PCDATA)>
<!ELEMENT misal (version*)>
<!ELEMENT version (#PCDATA)>
<!ATTLIST version tǝlam (ka|fa) #REQUIRED>

<!ELEMENT bowodu_gade (kalma, bowodu)>
<!ATTLIST bowodu_gade kandan IDREF #IMPLIED>

<!ELEMENT mane (kalma, bowodu)>
<!ATTLIST mane kandan IDREF #IMPLIED>

<!ELEMENT ngǝwula (kalma, bowodu)>
<!ATTLIST ngǝwula kandan IDREF #IMPLIED>

<!ELEMENT maana_tiloa (kalma, bowodu)>
<!ATTLIST maana_tiloa kandan IDREF #IMPLIED>

<!ELEMENT fǝrǝm (kalma, bowodu)>
<!ATTLIST fǝrǝm kandan IDREF #IMPLIED>

<!ELEMENT kǝnyakkuye_tilola (kalma, bowodu)>

<!ELEMENT kalakta (#PCDATA)>
<!ATTLIST kalakta tǝlam (ka|fa) #IMPLIED>

]>
<dilaf src="kau" trg="fra" version="1.3" datecreation="25/07/2017">
	<source>
		<ref>Soutéba. Dictionnaire kanouri-français. Enseignement du cycle de base 1, 2004</ref>
		<titre>Dictionnaire kanouri-français.</titre>
		<auteurs>Projet Soutien à l'Education de Base (Soutéba)</auteurs>
		<avertissement>Ce document est protégé par une licence Creative commons Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0). Il est obligatoire d'insérer dans les copies, extraits et versions modifiées de ce fichier le texte suivant : "Ressource issue du dictionnaire dilaf_kau_fra_v1.3.xml hébergée par le site web DiLAF www.dilaf.org. Il est interdit de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier sans faire mention de la même licence ; il est interdit d'utiliser commercialement les informations issues de ce fichier, des copies de ce fichier et des versions modifiées de ce fichier. Il est autorisé de copier ce fichier, de modifier ce fichier, de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier à condition de le faire avec la même licence.</avertissement>
		<license lien="https://creativecommons.org/licenses/by-nc-sa/2.0/">
		</license>
	</source>
   
	<article id="a1">
		<kalma>a</kalma>
		<bowodu>á</bowodu>
		<naptu_curo_nahauyen>aj.</naptu_curo_nahauyen>
		<bǝri id="a1_1">
			<maana>Kam awo ajabba curuiya bi fanjiya, wuljidǝ.</maana>
			<misal>
				<version tǝlam="ka">A ! Kuama lokkollo lenǝmi !</version>
			</misal>
			<kalakta tǝlam="fa">comment</kalakta>
		</bǝri>
	</article>
   
	<article id="a_a1">
		<kalma>a'a</kalma>
		<bowodu>á'à</bowodu>
		<naptu_curo_nahauyen>aj.</naptu_curo_nahauyen>
		<bǝri id="a_a1_1">
			<maana>Kam awo wajiya, wuljidǝ.</maana>
			<misal>
				<version tǝlam="ka">"A'a, ku kǝraro lekkiwawo !" yeno.</version>
			</misal>
			<kalakta tǝlam="fa">non</kalakta>
		</bǝri>
	</article>
   
	<article id="aaa1">
		<kalma>aaa</kalma>
		<bowodu>ààá</bowodu>
		<naptu_curo_nahauyen>aj.</naptu_curo_nahauyen>
		<bǝri id="aaa1_1">
			<maana>Kam awo cǝrayiya bi kasacciya, wuljidǝ.</maana>
			<misal>
				<version tǝlam="ka">"Aaa, ku kǝraro lekki !" yeno.</version>
			</misal>
			<kalakta tǝlam="fa">oui</kalakta>
		</bǝri>
	</article>
   
	<article id="abadaro1">
		<kalma>abadaro</kalma>
		<bowodu>àbàdárò</bowodu>
		<naptu_curo_nahauyen>nkye.</naptu_curo_nahauyen>
		<bǝri id="abadaro1_1">
			<maana>Awo yojiwaworo wuldidǝ.</maana>
			<misal>
				<version tǝlam="ka">Kǝri a buldu a abadaro na tilon napcaiwawo.</version>
			</misal>
			<kalakta tǝlam="fa">à jamais, jamais</kalakta>
		</bǝri>
	</article>
   
	<article id="abǝril1">
		<kalma>abǝril</kalma>
		<bowodu>àbǝ̀rîl</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="abǝril1_1">
			<maana>Kǝndawu nasara mewun yindindǝn ti dewuyedǝ.</maana>
			<misal>
				<version tǝlam="ka">Kǝmǝne jarapta burwoye abǝrillan kidiye.</version>
			</misal>
			<kalakta tǝlam="fa">avril</kalakta>
		</bǝri>
	</article>
   
	<article id="abǝr_wa1">
		<kalma>abǝɍwa</kalma>
		<bowodu>àbǝ̀ɍwà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="abǝr_wa1_1">
			<maana>Kǝska tǝngǝɍi, kalu ngǝwua dawulan tada cakkidǝ.</maana>
			<misal>
				<version tǝlam="ka">Kǝryende kannua nangaro, abǝɍwa cakkiwawo.</version>
			</misal>
			<kalakta tǝlam="fa">ananas</kalakta>
		</bǝri>
	</article>
   
	<article id="abǝr_wa2">
		<kalma>abǝɍwa</kalma>
		<bowodu>àbǝ̀ɍwà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="abǝr_wa2_1">
			<maana>Tada abǝɍwaye.</maana>
			<misal>
				<version tǝlam="ka">Abǝɍwa bafiya, jauro lelea.</version>
			</misal>
			<kalakta tǝlam="fa">fruit d'ananas</kalakta>
		</bǝri>
	</article>
   
	<article id="acca1">
		<kalma>acca</kalma>
		<bowodu>âccà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="acca1_1">
			<maana>Kamu Makkalan leje aji cǝde isǝnadǝ.</maana>
			<misal>
				<version tǝlam="ka">Acca nangaro, kullum kǝla jakkadaa lakkaro leji.</version>
			</misal>
			<mane kandan="hajja1">
				<kalma>hajja</kalma>
				<bowodu>hâjjà</bowodu>
			</mane>
			<kalakta tǝlam="fa">hadji (femme)</kalakta>
		</bǝri>
	</article>
   
	<article id="acca_ambe1">
		<kalma>acca ambe</kalma>
		<bowodu>âccà âmbè</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="acca_ambe1_1">
			<maana>Gǝmaje kamuwaye ngurumngurum kojiwawodǝ.</maana>
			<misal>
				<version tǝlam="ka">Jiyero tiro Makkalan acca ambe cakkudo.</version>
			</misal>
			<kalakta tǝlam="fa">robe de chambre</kalakta>
		</bǝri>
	</article>
   
	<article id="acca_gawara1">
		<kalma>acca gawara</kalma>
		<bowodu>âccà gáwárà</bowodu>
		<naptu_curo_nahauyen>cuk.</naptu_curo_nahauyen>
		<bǝri id="acca_gawara1_1">
			<maana>Batta jauro kamboi kamuwa tilan saraptaidǝ.</maana>
			<misal>
				<version tǝlam="ka">Tuworam ngǝwuso lamarro caluwiya, acca gawaralan tiyinja jakcai.</version>
			</misal>
			<kalakta tǝlam="fa">voile</kalakta>
		</bǝri>
	</article>
   
	<article id="accadu1">
		<kalma>accadu</kalma>
		<bowodu>àccàd̠ú</bowodu>
		<naptu_curo_nahauyen>kkye2.</naptu_curo_nahauyen>
		<bǝri id="accadu1_1">
			<maana>Accaro waldu.</maana>
			<misal>
				<version tǝlam="ka">Accaje kadinniya, koiyanjuro awo Makkalan curuna ngaa wuljiyi.</version>
			</misal>
			<kalakta tǝlam="fa">devenir hadji (femme)</kalakta>
		</bǝri>
	</article>
   
	<article id="aci_balbal1">
		<kalma>aci balbal</kalma>
		<bowodu>àcí bà̠lbà̠l</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="aci_balbal1_1">
			<maana>Gongon bi murta lowonia fitǝrol fijagane cattaidǝ.</maana>
			<misal>
				<version tǝlam="ka">Kure aci balbalma fatǝla wo.</version>
			</misal>
			<kalakta tǝlam="fa">lampe</kalakta>
		</bǝri>
	</article>
   
	<article id="ada1">
		<kalma>ada</kalma>
		<bowodu>ádà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="ada1_1">
			<maana>Awo kaan kaarinno tǝdidǝ.</maana>
			<misal>
				<version tǝlam="ka">Ada mangariyen larusa fǝrro ngojagai.</version>
			</misal>
			<kalakta tǝlam="fa">tradition</kalakta>
		</bǝri>
	</article>
   
	<article id="adada1">
		<kalma>adada</kalma>
		<bowodu>àdàdà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adada1_1">
			<maana>Ngǝrwo kura ci fadoyedǝ.</maana>
			<misal>
				<version tǝlam="ka">Ngǝwusoro amwurawa adadadǝa lesarambo kalakcai.</version>
			</misal>
			<kalakta tǝlam="fa">hangar</kalakta>
		</bǝri>
	</article>
   
	<article id="adal1">
		<kalma>adal</kalma>
		<bowodu>ádà̠l</bowodu>
		<naptu_curo_nahauyen>alnj.</naptu_curo_nahauyen>
		<bǝri id="adal1_1">
			<maana>Kam duwon kamanju jambaduro bi ndalduro majiwawodǝ.</maana>
			<misal>
				<version tǝlam="ka">Adal nangaro, wundu yaye yim kasuwua tia tassuji.</version>
			</misal>
			<kalakta tǝlam="fa">honnête</kalakta>
		</bǝri>
	</article>
   
	<article id="Adam1">
		<kalma>Adam</kalma>
		<bowodu>Ašdà̠m</bowodu>
		<naptu_curo_nahauyen>cuf.</naptu_curo_nahauyen>
		<bǝri id="Adam1_1">
			<maana>Kam burwon Kǝmandeye alakcǝnadǝ.</maana>
			<misal>
				<version tǝlam="ka">Alaye Adambo Auwaa kamuro keno.</version>
			</misal>
			<kalakta tǝlam="fa">Adam</kalakta>
		</bǝri>
	</article>
   
	<article id="adamgǝna1">
		<kalma>adamgǝna</kalma>
		<bowodu>ádà̠mgǝ̀nà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adamgǝna1_1">
			<maana>Kam.</maana>
			<misal>
				<version tǝlam="ka">Adamgǝna Alaro rijǝnama ngǝla wo.</version>
			</misal>
			<kalakta tǝlam="fa">être humain</kalakta>
		</bǝri>
	</article>
   
	<article id="adase1">
		<kalma>adase</kalma>
		<bowodu>àdàsé</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adase1_1">
			<maana>Am captane, sa sanin wuɍi kǝljane, ci ciyen wundu yaye ngojidǝ.</maana>
			<misal>
				<version tǝlam="ka">Adase laa kǝndawulan ngodi, laa ye mawulan ngodi.</version>
			</misal>
			<kalakta tǝlam="fa">tontine</kalakta>
		</bǝri>
	</article>
   
	<article id="adawar1">
		<kalma>adawar</kalma>
		<bowodu>ádáwà̠r</bowodu>
		<naptu_curo_nahauyen>alnj.</naptu_curo_nahauyen>
		<bǝri id="adawar1_1">
			<maana>Koro bi fǝr jiɍi buwubuwudǝ.</maana>
			<misal>
				<version tǝlam="ka">Fǝr adawar ngǝwu bawo.</version>
			</misal>
			<kalakta tǝlam="fa">souris (couleur)</kalakta>
		</bǝri>
	</article>
   
	<article id="adda1">
		<kalma>adda</kalma>
		<bowodu>àddá</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adda1_1">
			<maana>Su tǝgarǝna, taram kǝskayea, kǝɍin tiloa tilan kǝskaso caljaidǝ.</maana>
			<misal>
				<version tǝlam="ka">Kulonjuro lejiya, addanju a firdaiwawo.</version>
			</misal>
			<kalakta tǝlam="fa">machette, coupe-coupe</kalakta>
		</bǝri>
	</article>
   
	<article id="adǝ1">
		<kalma>adǝ</kalma>
		<bowodu>ád̠ǝ̀</bowodu>
		<naptu_curo_nahauyen>fǝl.</naptu_curo_nahauyen>
		<ngǝwula>
			<kalma>ani</kalma>
			<bowodu>ánì</bowodu>
		</ngǝwula>
		<bǝri id="adǝ1_1">
			<maana>Fǝledama awo fal karǝnne.</maana>
			<misal>
				<version tǝlam="ka">Ti adǝ lokkolma aji yindiye.</version>
			</misal>
			<kalakta tǝlam="fa">celui-ci</kalakta>
		</bǝri>
	</article>
   
	<article id="adǝ_nangaro1">
		<kalma>adǝ nangaro</kalma>
		<bowodu>ád̠ǝ̀ nàngàrò</bowodu>
		<naptu_curo_nahauyen>kǝl.</naptu_curo_nahauyen>
		<bǝri id="adǝ_nangaro1_1">
			<maana>Kalmawa curo manayen bayinno wuldidǝ.</maana>
			<misal>
				<version tǝlam="ka">Fannja kuruwulan, adǝ nangaro lokkollo isiya, kausu waldiwawo.</version>
			</misal>
			<kalakta tǝlam="fa">cause de (à), c'est pourquoi (c’est)</kalakta>
		</bǝri>
	</article>
   
	<article id="adǝgai1">
		<kalma>adǝgai</kalma>
		<bowodu>ád̠ǝ̀gǎ̠i</bowodu>
		<naptu_curo_nahauyen>nkye.</naptu_curo_nahauyen>
		<bǝri id="adǝgai1_1">
			<maana>Kalwo awo jussǝna wuljidǝ.</maana>
			<misal>
				<version tǝlam="ka">Jawa sawanjuye curune : "Adǝgai raakko," cǝne kasuwuro leyeno.</version>
			</misal>
			<kalakta tǝlam="fa">ainsi</kalakta>
		</bǝri>
	</article>
   
	<article id="adǝlamdu1">
		<kalma>adǝlamdu</kalma>
		<bowodu>àdǝ̀là̠md̠ú</bowodu>
		<bowodu_gade kandan="dǝlamdu1">
			<kalma>dǝlamdu</kalma>
			<bowodu>dǝ̀là̠md̠ú</bowodu>
		</bowodu_gade>
		<naptu_curo_nahauyen>kkye3.</naptu_curo_nahauyen>
		<bǝri id="adǝlamdu1_1">
			<maana>Kambe na ti bawolan diwinju manadu.</maana>
			<misal>
				<version tǝlam="ka">Tia adǝlamjai duwon, ise lawala kisango.</version>
			</misal>
			<kalakta tǝlam="fa">calomnier, diffamer</kalakta>
		</bǝri>
	</article>
   
	<article id="adidu1">
		<kalma>adidu</kalma>
		<bowodu>àdìd̠ú</bowodu>
		<naptu_curo_nahauyen>kkye3.</naptu_curo_nahauyen>
		<bǝri id="adidu1_1">
			<maana>Mana kuttu kambo wulduwu.</maana>
			<misal>
				<version tǝlam="ka">Awo kǝskero tia adije nansawanja bannajo.</version>
			</misal>
			<maana_tiloa kandan="landu1">
				<kalma>landu</kalma>
				<bowodu>lànd̠ú</bowodu>
			</maana_tiloa>
			<maana_tiloa kandan="radu1">
				<kalma>radu</kalma>
				<bowodu>ràd̠ú</bowodu>
			</maana_tiloa>
			<kalakta tǝlam="fa">insulter</kalakta>
		</bǝri>
	</article>
   
	<article id="adim1">
		<kalma>adim</kalma>
		<bowodu>ádìm</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adim1_1">
			<maana>Kam nadimjanadǝ.</maana>
			<misal>
				<version tǝlam="ka">Maiya kuye adimso cadanni.</version>
			</misal>
			<kalakta tǝlam="fa">eunuque</kalakta>
		</bǝri>
	</article>
   
	<article id="adin1">
		<kalma>adin</kalma>
		<bowodu>àdîn</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adin1_1">
			<maana>Jawal gaye Kǝmande kanjinjuro kamjǝgǝnadǝ.</maana>
			<misal>
				<version tǝlam="ka">Ala rijǝna nangaro, adin kalkallo jǝgai.</version>
			</misal>
			<kalakta tǝlam="fa">religion</kalakta>
		</bǝri>
	</article>
   
	<article id="adinma1">
		<kalma>adinma</kalma>
		<bowodu>àdìnmá</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adinma1_1">
			<maana>Kam jauro adinno kissǝgǝnadǝ.</maana>
			<misal>
				<version tǝlam="ka">Adinmaro kam adǝlamdudǝ jussǝnni.</version>
			</misal>
			<kalakta tǝlam="fa">pieux</kalakta>
		</bǝri>
	</article>
   
	<article id="adinnam1">
		<kalma>adinnam</kalma>
		<bowodu>àdînnà̠m</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adinnam1_1">
			<maana>Nijerlan kanji mǝsǝlǝm suwarde saɍijidǝ.</maana>
			<misal>
				<version tǝlam="ka">Kǝngal adinnamnin tambi.</version>
			</misal>
			<maana_tiloa kandan="gǝdi1">
				<kalma>gǝdi</kalma>
				<bowodu>gǝ̀dí</bowodu>
			</maana_tiloa>
			<kalakta tǝlam="fa">est</kalakta>
		</bǝri>
	</article>
   
	<article id="adinnamdaji1">
		<kalma>adinnamdaji</kalma>
		<bowodu>àdînnà̠mdàjí</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="adinnamdaji1_1">
			<maana>Adinnam kuruwu.</maana>
			<misal>
				<version tǝlam="ka">Defartema Difaye adinnamdaji Nijerren kǝrga.</version>
			</misal>
			<kalakta tǝlam="fa">extrême est</kalakta>
		</bǝri>
	</article>
   
	<article id="adinnamdu1">
		<kalma>adinnamdu</kalma>
		<bowodu>àdìnnà̠md̠ú</bowodu>
		<naptu_curo_nahauyen>kkye3.</naptu_curo_nahauyen>
		<bǝri id="adinnamdu1_1">
			<maana>Kǝla adinnambero ledu.</maana>
			<misal>
				<version tǝlam="ka">Maara ciyenniya, gǝna gǝnayen adinnamje Makkaro leyeno.</version>
			</misal>
			<kalakta tǝlam="fa">aller vers l'est</kalakta>
		</bǝri>
	</article>
   
	<article id="ado1">
		<kalma>ado</kalma>
		<bowodu>ádó</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="ado1_1">
			<maana>Tiyi bi awo gade candǝnaro dio.</maana>
			<misal>
				<version tǝlam="ka">Yim salaa wundu yaye ado cǝde culuwi.</version>
			</misal>
			<kalakta tǝlam="fa">maquillage</kalakta>
		</bǝri>
	</article>
   
	<article id="Afǝrika1">
		<kalma>Afǝrika</kalma>
		<bowodu>Àfǝ̀ríkà</bowodu>
		<naptu_curo_nahauyen>cuf.</naptu_curo_nahauyen>
		<bǝri id="Afǝrika1_1">
			<maana>Yaktu duniaye uwulan fal na larduwa am cǝlǝmbe ngǝwuadǝ.</maana>
			<misal>
				<version tǝlam="ka">Lardunde Nijerre curo Afǝrikayen kǝrga.</version>
			</misal>
			<kalakta tǝlam="fa">Afrique</kalakta>
		</bǝri>
	</article>
   
	<article id="afu1">
		<kalma>afu</kalma>
		<bowodu>áfù</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="afu1_1">
			<maana>Kunguna ganaaro diodǝ.</maana>
			<misal>
				<version tǝlam="ka">Kantima adǝ yadi afuaro sǝkkǝladǝna.</version>
			</misal>
			<kalakta tǝlam="fa">remise</kalakta>
		</bǝri>
	</article>
   
	<article id="afu2">
		<kalma>afu</kalma>
		<bowodu>áfù</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="afu2_1">
			<maana>Kam biwu cǝdǝnaye kurwowu sawo bi fuludu.</maana>
			<misal>
				<version tǝlam="ka">Kamceji afu gomnaye cuwandiwawo.</version>
			</misal>
			<kalakta tǝlam="fa">grâce</kalakta>
		</bǝri>
	</article>
   
	<article id="afudu1">
		<kalma>afudu</kalma>
		<bowodu>àfùd̠ú</bowodu>
		<naptu_curo_nahauyen>kkye3.</naptu_curo_nahauyen>
		<bǝri id="afudu1_1">
			<maana>Afu2 njo.</maana>
			<misal>
				<version tǝlam="ka">Barga salaye nangaro, gomna larduye kosowu laa laa afujǝna.</version>
			</misal>
			<kalakta tǝlam="fa">gracier</kalakta>
		</bǝri>
	</article>
   
	<article id="afuno1">
		<kalma>afuno</kalma>
		<bowodu>àfùnó</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="afuno1_1">
			<maana>Am Nijerlan ngǝwusoro dawu larduyen kaan kaarinno dasaanadǝ.</maana>
			<misal>
				<version tǝlam="ka">Afuno wuɍi madaro na kuruwuro leji.</version>
			</misal>
			<kalakta tǝlam="fa">haoussa</kalakta>
		</bǝri>
	</article>
   
	<article id="afuno2">
		<kalma>afuno</kalma>
		<bowodu>àfùnó</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="afuno2_1">
			<mane kandan="afunoafuno2">
				<kalma>afunoafuno</kalma>
				<bowodu>àfùnòàfùnó</bowodu>
			</mane>
		</bǝri>
	</article>
   
	<article id="afunoafuno1">
		<kalma>afunoafuno</kalma>
		<bowodu>àfùnòàfùnó</bowodu>
		<bowodu_gade kandan="afuno1">
			<kalma>afuno</kalma>
			<bowodu>àfùnó</bowodu>
		</bowodu_gade>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="afunoafuno1_1">
			<maana>Tǝlam afunowa jandejaidǝ.</maana>
			<misal>
				<version tǝlam="ka">Am lardu Nijerre ngǝwuso afunoafuno fanjai, bi manajai.</version>
			</misal>
			<kalakta tǝlam="fa">haoussa</kalakta>
		</bǝri>
	</article>
   
	<article id="afunoafuno2">
		<kalma>afunoafuno</kalma>
		<bowodu>àfùnòàfùnó</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="afunoafuno2_1">
			<maana>Fudu afuno gairo.</maana>
			<misal>
				<version tǝlam="ka">Gǝmajenju afunoafunoro cududǝna.</version>
			</misal>
			<kalakta tǝlam="fa">haoussa (manière du)</kalakta>
		</bǝri>
	</article>
   
	<article id="afunoram1">
		<kalma>afunoram</kalma>
		<bowodu>àfùnórà̠m</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="afunoram1_1">
			<maana>Fero bi kamu afunodǝ.</maana>
			<misal>
				<version tǝlam="ka">Sawani afunoram kamuro ngoyeno.</version>
			</misal>
			<kalakta tǝlam="fa">haoussa (fille ou femme)</kalakta>
		</bǝri>
	</article>
   
	<article id="Agadas1">
		<kalma>Agadas</kalma>
		<bowodu>Ašgádà̠s</bowodu>
		<naptu_curo_nahauyen>cuf.</naptu_curo_nahauyen>
		<bǝri id="Agadas1_1">
			<maana>Agadasdǝ kǝrye wusku lardu Nijerre falnju yalan dǝganadǝ.</maana>
			<misal>
				<version tǝlam="ka">Kǝrye Agadasselan defartema yakku : Arlit, Bilma, Anu Araren.</version>
			</misal>
		</bǝri>
	</article>
   
	<article id="Agar1">
		<kalma>Agar</kalma>
		<bowodu>á̠gà̠r</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="Agar1_1">
			<maana>Kǝska sorsor tilan kǝla ngimbe cadidǝ.</maana>
			<misal>
				<version tǝlam="ka">Kǝla ngimnjuye agar findilan kido.</version>
			</misal>
			<kalakta tǝlam="fa">lattis (une)</kalakta>
		</bǝri>
	</article>
   
	<article id="agaram1">
		<kalma>agaram</kalma>
		<bowodu>àgàrám</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="agaram1_1">
			<maana>Kǝlanga kartaye karta uwu uwu dagarjane cadidǝ.</maana>
			<misal>
				<version tǝlam="ka">Yim niya Moduyea am laa agaram cadi, laa kos cadi dabduyera.</version>
			</misal>
			<kalakta tǝlam="fa">jeu de cartes</kalakta>
		</bǝri>
	</article>
   
	<article id="Age1">
		<kalma>Age</kalma>
		<bowodu>Àgé</bowodu>
		<naptu_curo_nahauyen>cuf.</naptu_curo_nahauyen>
		<bǝri id="Age1_1">
			<maana>Bǝrni naptu bǝla kura defartemaye cǝdi katte Maradi a Tasawa ayelan dǝganadǝ.</maana>
			<misal>
				<version tǝlam="ka">Ageye yalanjulan departema Mayayiye.</version>
			</misal>
			<kalakta tǝlam="fa">Aguie</kalakta>
		</bǝri>
	</article>
   
	<article id="agǝl1">
		<kalma>agǝl</kalma>
		<bowodu>á̠gǝ̀l</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="agǝl1_1">
			<maana>Kǝska kajaaye bi kǝniwusoyedǝ.</maana>
			<misal>
				<version tǝlam="ka">Agǝl kajaanjuye si bidoye.</version>
			</misal>
			<kalakta tǝlam="fa">hampe</kalakta>
		</bǝri>
	</article>
   
	<article id="agǝri1">
		<kalma>agǝri</kalma>
		<bowodu>ágǝ̀rì</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="agǝri1_1">
			<maana>Wuɍi biyanǝme karenǝm lǝmannin bi motalan caadi.</maana>
			<misal>
				<version tǝlam="ka">Ku Maduro jǝkka uwu agǝri koronjuyeye cakkudo.</version>
			</misal>
			<kalakta tǝlam="fa">location</kalakta>
		</bǝri>
	</article>
   
	<article id="agǝridu1">
		<kalma>agǝridu</kalma>
		<bowodu>àgǝ̀rìd̠ú</bowodu>
		<naptu_curo_nahauyen>kkye3.</naptu_curo_nahauyen>
		<bǝri id="agǝridu1_1">
			<maana>Agǝri dio.</maana>
			<misal>
				<version tǝlam="ka">Manua mota agǝrije lakka gadero bǝrdǝna.</version>
			</misal>
			<kalakta tǝlam="fa">louer</kalakta>
		</bǝri>
	</article>
   
	<article id="agogo1">
		<kalma>agogo</kalma>
		<bowodu>àgógó</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="agogo1_1">
			<maana>Sa fǝleduma.</maana>
			<misal>
				<version tǝlam="ka">Agogo jiɍi kada : mukkoye, ngimbe, motaye.</version>
			</misal>
			<kalakta tǝlam="fa">montre, horloge, pendule, réveil</kalakta>
		</bǝri>
	</article>
   
	<article id="agogoma1">
		<kalma>agogoma</kalma>
		<bowodu>àgógómà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="agogoma1_1">
			<maana>Kam agogo cassai bi cǝladidǝ.</maana>
			<misal>
				<version tǝlam="ka">Agogoma tulyenniya, agogonju dajiwaworo walyeno.</version>
			</misal>
			<kalakta tǝlam="fa">horloger</kalakta>
		</bǝri>
	</article>
   
	<article id="agwagwa1">
		<kalma>agwagwa</kalma>
		<bowodu>àgwàgwá</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="agwagwa1_1">
			<maana>Ngudo fadoye, si fatatalla, na ingia jaumaro cǝragǝnadǝ.</maana>
			<misal>
				<version tǝlam="ka">Kuɍi maji cǝne agwagwa fado sammaa laji.</version>
			</misal>
			<kalakta tǝlam="fa">canard de Barbarie</kalakta>
		</bǝri>
	</article>
   
	<article id="aiya1">
		<kalma>aiya</kalma>
		<bowodu>ǎ̠iyá</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="aiya1_1">
			<maana>Kowo kǝjiro dime mana cilan tuluwumidǝ.</maana>
			<misal>
				<version tǝlam="ka">Festibal 1982yelan aiya ferowa Bosoye burwoyero waljo.</version>
			</misal>
			<kalakta tǝlam="fa">chanson</kalakta>
		</bǝri>
	</article>
   
	<article id="aiyaduri1">
		<kalma>aiyaduri</kalma>
		<bowodu>á̠iyádúrì</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="aiyaduri1_1">
			<maana>Bune mauluduyen yallaye fǝrraro jawane bǝladeyaro ngǝrǝmbaro ledudǝ.</maana>
			<misal>
				<version tǝlam="ka">Aiyaduri diye duwon, sawania fǝr yapkeyeno.</version>
			</misal>
			<kalakta tǝlam="fa">course de chevaux (nuit de mouloud)</kalakta>
		</bǝri>
	</article>
   
	<article id="aiyama1">
		<kalma>aiyama</kalma>
		<bowodu>ǎ̠iyámà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="aiyama1_1">
			<maana>Aiya dioma.</maana>
			<misal>
				<version tǝlam="ka">Kam kowo kuttua aiyama ngǝlaro waljiwawo.</version>
			</misal>
			<kalakta tǝlam="fa">chanteur</kalakta>
		</bǝri>
	</article>
   
	<article id="aja1">
		<kalma>aja</kalma>
		<bowodu>àjâ</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="aja1_1">
			<maana>Yim laaro faidajo nangaro wuɍi bi lǝman gade gǝnadudǝ.</maana>
			<misal>
				<version tǝlam="ka">Ajanjulan Makka biyaje leyeno.</version>
			</misal>
			<kalakta tǝlam="fa">dépôt, épargne</kalakta>
		</bǝri>
	</article>
   
	<article id="ajabba1">
		<kalma>ajabba</kalma>
		<bowodu>ájà̠bbà</bowodu>
		<naptu_curo_nahauyen>alnj.</naptu_curo_nahauyen>
		<bǝri id="ajabba1_1">
			<maana>Awo tǝmanǝmmi wakkajidǝ.</maana>
			<misal>
				<version tǝlam="ka">Ajabba gǝni, Kǝmandeyen kadioa.</version>
			</misal>
			<kalakta tǝlam="fa">étonnant, bizarre</kalakta>
		</bǝri>
	</article>
   
	<article id="ajabba2">
		<kalma>ajabba</kalma>
		<bowodu>ájà̠bbà</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="ajabba2_1">
			<maana>Kalma tilan karwukǝji bi karwukutta bi awo ajapkadasoro wuldidǝ.</maana>
			<misal>
				<version tǝlam="ka">Ha ! Wua maskalan bansi ! "Ha !" tima ajabba wo.</version>
			</misal>
			<kalakta tǝlam="fa">interjection</kalakta>
		</bǝri>
	</article>
   
	<article id="ajadu1">
		<kalma>ajadu</kalma>
		<bowodu>àjàd̠ú</bowodu>
		<naptu_curo_nahauyen>kkye3.</naptu_curo_nahauyen>
		<bǝri id="ajadu1_1">
			<maana>Aja dio.</maana>
			<misal>
				<version tǝlam="ka">Wuɍinju ajajǝnadǝlan fe yindi kaiwo.</version>
			</misal>
			<kalakta tǝlam="fa">épargner</kalakta>
		</bǝri>
	</article>
   
	<article id="ajaja1">
		<kalma>ajaja</kalma>
		<bowodu>àjàjá</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="ajaja1_1">
			<maana>Awo tilan buwu argǝmbeso cadidǝ.</maana>
			<misal>
				<version tǝlam="ka">Bare ɍimjǝnniro, goro so, lemǝn so ajaja yiyapkadalan jakcai.</version>
			</misal>
			<kalakta tǝlam="fa">toile de jute</kalakta>
		</bǝri>
	</article>
   
	<article id="ajal1">
		<kalma>ajal</kalma>
		<bowodu>ájà̠l</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="ajal1_1">
			<maana>Awo kuttu dunialan kambo Kǝmande gǝnajiyidǝ.</maana>
			<misal>
				<version tǝlam="ka">Ajalnju cǝne kannu fannju giwunniya, kanadi ngoyeno.</version>
			</misal>
			<kalakta tǝlam="fa">sort</kalakta>
		</bǝri>
	</article>
   
	<article id="ajal2">
		<kalma>ajal</kalma>
		<bowodu>ájà̠l</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="ajal2_1">
			<maana>Awo ɍiwullalan tǝgarǝna ngasuro casakkidǝ.</maana>
			<misal>
				<version tǝlam="ka">Mangarilan fero ngodǝnni ajal cakkiwawo.</version>
			</misal>
			<kalakta tǝlam="fa">bracelet</kalakta>
		</bǝri>
	</article>
   
	<article id="ajaldu1">
		<kalma>ajaldu</kalma>
		<bowodu>àjàld̠ú</bowodu>
		<naptu_curo_nahauyen>kkye3.</naptu_curo_nahauyen>
		<bǝri id="ajaldu1_1">
			<maana>Doidoiro awo laa dio.</maana>
			<misal>
				<version tǝlam="ka">Musa ajaljǝna, kawu dunia wajimaro.</version>
			</misal>
			<maana_tiloa kandan="gandu2">
				<kalma>gandu</kalma>
				<bowodu>gánd̠ú</bowodu>
			</maana_tiloa>
			<kalakta tǝlam="fa">presser (se), dépêcher (se)</kalakta>
		</bǝri>
	</article>
   
	<article id="ajama1">
		<kalma>ajama</kalma>
		<bowodu>ájàmá</bowodu>
		<naptu_curo_nahauyen>cu.</naptu_curo_nahauyen>
		<bǝri id="ajama1_1">
			<maana>Ngawuɍi bul fokdǝ.</maana>
			<misal>
				<version tǝlam="ka">Kasuwuro lejiya, bǝrabusko dioro ajama ngalji.</version>
			</misal>
			<kalakta tǝlam="fa">sorgho blanc</kalakta>
		</bǝri>
	</article>
   
	<article id="ajap1">
		<kalma>ajap</kalma>
		<bowodu>ájà̠p</bowodu>
		<naptu_curo_nahauyen>aj.</naptu_curo_nahauyen>
		<bǝri id="ajap1_1">
			<maana>Awo tǝmanǝmmi isiya bi rumiya, wullǝmidǝ.</maana>
			<misal>
				<version tǝlam="ka">Ajap ! Jiɍi finin Difalan cije Niamero silan leyeno !</version>
			</misal>
			<kalakta tǝlam="fa">étonnant (c'est)</kalakta>
		</bǝri>
	</article>
   
	<article id="ajaptu1">
		<kalma>ajaptu</kalma>
		<bowodu>àjà̠ptú</bowodu>
		<naptu_curo_nahauyen>kkye3.</naptu_curo_nahauyen>
		<bǝri id="ajaptu1_1">
			<maana>Naptu kam awo ajabba curuna bi fanjǝnaye dio.</maana>
			<misal>