<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="application/xml" href="tamajaq_v9.xsl"?>

<!-- 
Auteurs version papier : projet SouTéBa
Rédacteur en chef : Elghamis Ramada
Lexicographes : Ahmed Mahmoud, Elghamis Ramada, Kadaï Alhassen, Modi Issouf, Mme Manou née Zara Villain
Responsable principal : Thomas Büttner
Coordinateur académique : Mallam Garba Maman

Auteurs version XML : projet DiLAF
Coordinatrice : Chantal Enguehard
Responsable informatique 2010-2016 : Mathieu Mangeot
Stagiaire Université de Nantes 2014-2015 : Alicia Boucard

Publication de référence : Mathieu Mangeot & Chantal Enguehard (2013) Des dictionnaires éditoriaux aux représentations XML standardisées. Chaptre 8, livre "Ressources Lexicales : contenu, construction, utilisation, évaluation", Eds. Nuria Gala & Michael Zock, Linguisticae Investigationes Supplementa, John Benjamins Publishing, Amsterdam, Pays-Bas, 24 p.

Date : 25/07/2017
Version : 1.3
Licence : Creative Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0) : http://creativecommons.org/licenses/by-nc-sa/2.0/
-->

<!DOCTYPE dilaf [
<!ELEMENT dilaf (source, albab*)>
<!ATTLIST dilaf src CDATA #REQUIRED>
<!ATTLIST dilaf trg CDATA #REQUIRED>
<!ATTLIST dilaf version CDATA #REQUIRED>
<!ATTLIST dilaf datecreation CDATA #REQUIRED>

<!ELEMENT source (ref*, titre, auteurs, avertissement, license)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (#PCDATA)>
<!ELEMENT avertissement (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license lien CDATA #IMPLIED>

<!ELEMENT albab (təzugəst, təmuṣt, variante_cat?, tazezlit?, əsəfsəs?, igət*, tastəqY?, tastəqW*, əlfiɣšǎt)>
<!ATTLIST albab id ID #REQUIRED>

<!ELEMENT əlfiɣšǎt (almaɣna?, təfaransist?, ǎkku*, əlmisal*, anammelu*, anəmmezrəy*)>
<!ATTLIST əlfiɣšǎt id ID #REQUIRED>

<!ELEMENT təzugəst (#PCDATA)>

<!ELEMENT təmuṣt (#PCDATA)>
<!ELEMENT variante_cat (#PCDATA)>
<!ELEMENT tazezlit (#PCDATA)>
<!ELEMENT almaɣna (#PCDATA)>
<!ELEMENT təfaransist (#PCDATA)>

<!ELEMENT ǎkku (#PCDATA)>
<!ATTLIST ǎkku sadderan IDREF #IMPLIED>

<!ELEMENT əlmisal (#PCDATA)>

<!ELEMENT anəmmezrəy (#PCDATA)>
<!ATTLIST anəmmezrəy sadderan IDREF #IMPLIED>

<!ELEMENT əsəfsəs (#PCDATA)>
<!ELEMENT igət (#PCDATA)>
<!ELEMENT tastəqY (#PCDATA)>
<!ELEMENT tastəqW (#PCDATA)>

<!ELEMENT anammelu (#PCDATA)>
<!ATTLIST anammelu sadderan IDREF #IMPLIED>
]>
<dilaf src="tmh" trg="fra" version="1.3" datecreation="25/07/2017">

	<source>
		<ref>Soutéba. Dictionnaire tamajaq-français. Enseignement du cycle de base 1, 2007</ref>
		<titre>Dictionnaire tamajaq-français.</titre>
		<auteurs>Projet Soutien à l'Education de Base (Soutéba)</auteurs>
		<avertissement>Ce document est protégé par une licence Creative commons Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0). Il est obligatoire d'insérer dans les copies, extraits et versions modifiées de ce fichier le texte suivant : "Ressource issue du dictionnaire dilaf_tmh_fra_v1.3.xml hébergée par le site web DiLAF www.dilaf.org. Il est interdit de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier sans faire mention de la même licence ; il est interdit d'utiliser commercialement les informations issues de ce fichier, des copies de ce fichier et des versions modifiées de ce fichier. Il est autorisé de copier ce fichier, de modifier ce fichier, de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier à condition de le faire avec la même licence.</avertissement>
		<license lien="https://creativecommons.org/licenses/by-nc-sa/2.0/">
		</license>
	</source>
	
	<albab id="aba1">
		<təzugəst>ǎba</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="aba1_1">
			<almaɣna>Ebətti n ǎrǎt medǎɣ ag-adəm.</almaɣna>
			<təfaransist>absent, décédé</təfaransist>
			<əlmisal>As ǎba awedən ad əlin marawǎn-net.</əlmisal>
			<anammelu>bǎttǎt</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abada1">
		<təzugəst>ǎbada</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibadan</igət>
		<əlfiɣšǎt id="abada1_1">
			<almaɣna>Daw tədist.</almaɣna>
			<təfaransist>bas-ventre</təfaransist>
			<əlmisal>Bǎrar wa yəllûẓǎn ad t-yəltəɣ ǎbada-net.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abada2">
		<təzugəst>ǎbada</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ibadan</igət>
		<əlfiɣšǎt id="abada2_1">
			<almaɣna>Tasǎga meɣ daw ǎdǎg əyyǎn.</almaɣna>
			<təfaransist>flanc</təfaransist>
			<əlmisal>Iməwwəẓla əklǎn dǎɣ ǎbada n əkašwar.</əlmisal>
			<anammelu>azador</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abada3">
		<təzugəst>ǎbada</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibadan</igət>
		<əlfiɣšǎt id="abada3_1">
			<almaɣna>Edǎg wa dǎɣ təsâgǎwǎr təmṭət bǎrar-net təṭṭəf-tu.</almaɣna>
			<təfaransist>devant soi</təfaransist>
			<əlmisal>Xawa təga bǎrar-net dǎɣ ǎbada tənsa.</əlmisal>
			<anammelu sadderan="dat1">dat</anammelu>
			<anammelu>asakkalammo</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abaḍabaḍ1">
		<təzugəst>abaḍabaḍ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ibaḍabaḍǎn</igət>
		<əlfiɣšǎt id="abaḍabaḍ1_1">
			<almaɣna>Edǎg yəkkâlǎn.</almaɣna>
			<təfaransist>sommet, faîte, point culminant</təfaransist>
			<əlmisal>Musa as yewǎl ad yəwər afalla n abaḍabaḍ n əkašwar əyyǎn.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abadagdag1">
		<təzugəst>abadǎgdǎg</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ibadǎgdǎgǎn</igət>
		<əlfiɣšǎt id="abadagdag1_1">
			<almaɣna>Amǎḍal yəgdân, yəssəxen dǎɣ wər d-yəgəmməḍ ələmmuẓ, yəzâzgar aman.</almaɣna>
			<təfaransist>plaine</təfaransist>
			<əlmisal>Ǝnḍaẓəl əṭṭəbəl-nǎna yəgâɣ amnəy fel ǎbadǎgdǎg wa n əṣəwi.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abago1">
		<təzugəst>abǎgo</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ibǎgotǎn</igət>
		<əlfiɣšǎt id="abago1_1">
			<almaɣna>Yel d-yəsâkṭin abazay.</almaɣna>
			<təfaransist>espèce de plante</təfaransist>
			<əlmisal>Aɣalak tâggin amǎgal s ǎbǎgo.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abago2">
		<təzugəst>abǎgo</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əlfiɣšǎt id="abago2_1">
			<almaɣna>Ǝkənbəb ən tezay ən taləmt igan s akor megh əgašek igadalan i rures anakas n əx.</almaɣna>
			<təfaransist>cache-mamelle (morceau en toile ou en cuir avec lequel on ferme la mamelle d’une chamelle pour empêcher son petit de téter le lait)</təfaransist>
		</əlfiɣšǎt>
	</albab>

	<albab id="abagog1">
		<təzugəst>abagog</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>əbgag</igət>
		<tastəqW>abagog : aw tilay wa zəwwaran iddazan</tastəqW>
		<əlfiɣšǎt id="abagog1_1">
			<almaɣna>Aw-tǎle wa məḍərrǎn.</almaɣna>
			<təfaransist>mouton, ovin</təfaransist>
			<əlmisal>As yərin Amaloz yəgzǎm-as abba-net abagog yəddəren.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abagog2">
		<təzugəst>abagog</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əlfiɣšǎt id="abagog2_1">
			<almaɣna>Aw-tǎle iddazan ilan karad elan.</almaɣna>
			<təfaransist>grand mouton castré</təfaransist>
		</əlfiɣšǎt>
	</albab>

	<albab id="abaka1">
		<təzugəst>abǎka</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibǎkan</igət>
		<igət>ibǎkatǎn</igət>
		<əlfiɣšǎt id="abaka1_1">
			<almaɣna>Ešək wa yətârawǎn izəggarǎn.</almaɣna>
			<təfaransist>jujubier</təfaransist>
			<əlmisal>Kǎya yəfâṭṭǎn abǎka fel a dd-yəkkəs izəggarǎn.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abakkaḍ1">
		<təzugəst>abakkaḍ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibakkaḍǎn</igət>
		<əlfiɣšǎt id="abakkaḍ1_1">
			<almaɣna>Igi n ǎrǎt wər nəmmol.</almaɣna>
			<təfaransist>péché</təfaransist>
			<əlmisal>Bǎrar n ənəsləm as tu-təff-e isan n ǎladǎy təge abakkaḍ.</əlmisal>
			<anəmmezrəy sadderan="alxer1">alxer</anəmmezrəy>
			<anəmmezrəy>maggǎt</anəmmezrəy>
		</əlfiɣšǎt>
	</albab>

	<albab id="abakot1">
		<təzugəst>abǎkot</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>əbkat</igət>
		<əlfiɣšǎt id="abakot1_1">
			<almaɣna>Egašek waššarǎn.</almaɣna>
			<təfaransist>peau usée</təfaransist>
			<əlmisal>Enǎḍ yəkânnu aləkkuḍ dǎɣ ǎbǎkot ən tasṭ.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abalaɣlaɣ1">
		<təzugəst>abǎlǎɣlǎɣ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibalǎɣlǎɣǎn</igət>
		<əlfiɣšǎt id="abalaɣlaɣ1_1">
			<almaɣna>Aman-aman wi n kǎwalnin wi n d-ənâqqalnin dǎɣ ešək.</almaɣna>
			<təfaransist>sève noire de l'acacia</təfaransist>
			<əlmisal>Yəlle-tu ǎbǎlǎɣlǎɣ wa yəgǎn tikǎḍamḍǎmen.</əlmisal>
			<anammelu>taḍǎmsanǎt</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abalaɣlaɣ2">
		<təzugəst>abǎlǎɣlǎɣ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əlfiɣšǎt id="abalaɣlaɣ2_1">
			<almaɣna>Arat ən tatənghen n ašək.</almaɣna>
			<təfaransist>graine huileuse de l'acacia</təfaransist>
		</əlfiɣšǎt>
	</albab>

	<albab id="abalboḍ1">
		<təzugəst>abalboḍ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibəlbaḍ</igət>
		<əlfiɣšǎt id="abalboḍ1_1">
			<almaɣna>Agbəḍ yəgân dǎɣ talašše wa dǎɣ ɣâbbarnǎt təḍoḍen ilalǎn-nǎsnǎt.</almaɣna>
			<təfaransist>sac en tissu (femme)</təfaransist>
			<əlmisal>Anna-nǎna təqqǎn imi n ǎbalboḍ-net s əẓẓəmi fel ma nokǎr taba-net.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abaraḍ1">
		<təzugəst>abaraḍ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibaraḍǎn</igət>
		<əlfiɣšǎt id="abaraḍ1_1">
			<almaɣna>Eləs wa n anammagǎr wər tǎha tǎsa.</almaɣna>
			<təfaransist>brave</təfaransist>
			<əlmisal>Abaraḍ ənta a yətâkkin emgər.</əlmisal>
			<anammelu>alɣoɣ</anammelu>
			<anəmmezrəy sadderan="amalɣon1">amalɣon</anəmmezrəy>
		</əlfiɣšǎt>
	</albab>

	<albab id="abarag1">
		<təzugəst>abǎrag</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibǎragǎn</igət>
		<əlfiɣšǎt id="abarag1_1">
			<almaɣna>Esəfləs ən man.</almaɣna>
			<təfaransist>vantardise</təfaransist>
			<əlmisal>Anasbehu wər dǎɣ-as ətiba ibǎragǎn.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abaranberu1">
		<təzugəst>ǎbǎrǎnberu</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>əbrənbura</igət>
		<əlfiɣšǎt id="abaranberu1_1">
			<almaɣna>Edǎg dǎɣ ətîwajarakkǎt ǎmǎḍal.</almaɣna>
			<təfaransist>trou dans le sol</təfaransist>
			<əlmisal>Iji as tu-təqqǎḍ təfuk ad yəgu ǎbǎrǎnberu daw ešək yəgən.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abaraqqa1">
		<təzugəst>abaraqqa</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibarraqqan</igət>
		<əlfiɣšǎt id="abaraqqa1_1">
			<təfaransist>chemin, route</təfaransist>
			<ǎkku sadderan="tarrayt2">tarrǎyt</ǎkku>
			<əlmisal>Iməwwəẓla əgǎn abaraqqa i əmnas-nǎsǎn dǎɣ adɣaɣ.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abašanšar1">
		<təzugəst>abašanšar</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibašanšarǎn</igət>
		<əlfiɣšǎt id="abašanšar1_1">
			<almaɣna>Er s əkkârǎn ənšerǎn tənjart-net ak ǎlaq.</almaɣna>
			<təfaransist>morveux</təfaransist>
			<əlmisal>Abašanšar wər ǎhor əd tədrəwt n əšənk.</əlmisal>
			<anammelu>in-ənšarǎn</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abatol1">
		<təzugəst>abǎtol</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ibətal</igət>
		<igət>ibətlan</igət>
		<igət>əbtal</igət>
		<əlfiɣšǎt id="abatol1_1">
			<almaɣna>Edǎg yərâṣǎn dǎɣ ǎmǎḍal egas yoglâ ərəkken, mera yətâwǎy aman.</almaɣna>
			<təfaransist>fosse, creux, cuvette</təfaransist>
			<əlmisal>Bahi yewâl ihərwan-net dǎɣ ǎbǎtol iyyǎn, as t-yəɣdǎr kayni yəcc-as taɣidət.</əlmisal>
			<anammelu>alabǎqqo</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abattabor1">
		<təzugəst>abattǎbor</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibattǎborǎn</igət>
		<əlfiɣšǎt id="abattabor1_1">
			<almaɣna>Teffart n əyəs.</almaɣna>
			<təfaransist>entrave (cheval)</təfaransist>
			<əlmisal>Eyəs-nǎna as yəɣtǎs abattǎbor-net yəwəqqǎs.</əlmisal>
			<anammelu>abattǎbar</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abattabor2">
		<təzugəst>abattǎbor</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əlfiɣšǎt id="abattabor2_1">
			<almaɣna>Agət wa dagh itaqqan ays madegh awara.</almaɣna>
			<təfaransist>piquet pour attacher un cheval ou un chamelon</təfaransist>
		</əlfiɣšǎt>
	</albab>

	<albab id="abaya1">
		<təzugəst>abǎya</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibǎyan</igət>
		<əlfiɣšǎt id="abaya1_1">
			<təfaransist>urine</təfaransist>
			<ǎkku sadderan="imənɣal1">imənɣal</ǎkku>
			<anammelu sadderan="imənɣal1">imənɣal</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abaydaɣor1">
		<təzugəst>abaydaɣor</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibaydaɣorǎn</igət>
		<əlfiɣšǎt id="abaydaɣor1_1">
			<təfaransist>gaule</təfaransist>
			<ǎkku sadderan="as_kom1">aṣkom</ǎkku>
			<anammelu>askom</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abaykor1">
		<təzugəst>abaykor</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibəykar</igət>
		<əlfiɣšǎt id="abaykor1_1">
			<almaɣna>Iji wa waššarǎn təwǎr allaɣanǎt.</almaɣna>
			<təfaransist>vieux chien</təfaransist>
			<əlmisal>Ǝngom əmmînǎya d ənagmar s yəlkâm abaykor.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abazay1">
		<təzugəst>abǎzǎy</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibǎzǎyǎn</igət>
		<əlfiɣšǎt id="abazay1_1">
			<almaɣna>Yel əs kânnin aɣalak ədgi s əflawǎn-net as yəqqur, sâtanfarǎn-tu.</almaɣna>
			<təfaransist>dolique, cassia tora (plante)</təfaransist>
			<əlmisal>Bǎrarǎn tinəməndibǎn əs marrǎn n ǎbazǎy.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abəd1">
		<təzugəst>abəd</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="abəd1_1">
			<almaɣna>Igi n ǎrǎt fǎwda.</almaɣna>
			<təfaransist>se consacrer</təfaransist>
			<əlmisal>Enəsləm yobâd emud ən fǎw.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abəyoɣ1">
		<təzugəst>abəyoɣ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ə</əsəfsəs>
		<igət>əbyaɣ</igət>
		<əlfiɣšǎt id="abəyoɣ1_1">
			<almaɣna>Ǝmutǎg yəgân dǎɣ egašek fel esənsi n aman.</almaɣna>
			<təfaransist>outre</təfaransist>
			<əlmisal>Imazragǎn əzzəkanǎn əjzḍan-nǎsǎn əbyaɣ.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abəyoɣ2">
		<təzugəst>abəyoɣ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>əbyaɣ</igət>
		<əlfiɣšǎt id="abəyoɣ2_1">
			<almaɣna>Ǝmutǎg ən fətəla wa yətâggǎz kələnzir.</almaɣna>
			<təfaransist>réservoir</təfaransist>
			<əlmisal>Abəyəɣ ən fətəla-nin yəstǎg tərmaḍ.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abḍət1">
		<təzugəst>abḍət</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="abḍət1_1">
			<almaɣna>Ezuzəl n aḷǎm.</almaɣna>
			<təfaransist>galoper</təfaransist>
			<əlmisal>Lilla yobḍât aḷǎm-net as d-yəgmǎḍ Gani.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abela1">
		<təzugəst>ǎbela</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ibelan</igət>
		<əlfiɣšǎt id="abela1_1">
			<almaɣna>Ebabbal ən tamse təkkât əjənna.</almaɣna>
			<təfaransist>flamme, feu</təfaransist>
			<əlmisal>Bǎrarǎn əgǎn ǎbela n tamse ofǎrǎn igi n mayyǎn.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="aber1">
		<təzugəst>aber</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>a</əsəfsəs>
		<igət>iberǎn</igət>
		<əlfiɣšǎt id="aber1_1">
			<almaɣna>Awa s yəšâkkǎr awedən əmudǎr.</almaɣna>
			<təfaransist>trace</təfaransist>
			<əlmisal>Aber n əwərkəd yəsâkṭa-du wa n bǎrar.</əlmisal>
			<anammelu sadderan="edəriz1">edəriz</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aber2">
		<təzugəst>aber</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>iberǎn</igət>
		<əlfiɣšǎt id="aber2_1">
			<təfaransist>piste</təfaransist>
			<ǎkku sadderan="tarrayt1">tarrǎyt</ǎkku>
			<anammelu sadderan="eber1">eber</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abləɣ1">
		<təzugəst>abləɣ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibəlɣan</igət>
		<əlfiɣšǎt id="abləɣ1_1">
			<almaɣna>Təbluleq ən tǎlaq.</almaɣna>
			<təfaransist>motte d'argile</təfaransist>
			<əlmisal>Musa yəkkǎl abləɣ ən tǎlaq yəgǎr sər-əs iji.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abləɣ2">
		<təzugəst>abləɣ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ibəlɣan</igət>
		<əlfiɣšǎt id="abləɣ2_1">
			<almaɣna>Aganna n təkkəst n əṣṣukər meɣ tisəmt.</almaɣna>
			<təfaransist>morceau de sucre ou de sel</təfaransist>
			<əlmisal>Adda yaššewǎy i ənarag-net abləɣ n əṣṣukər.</əlmisal>
			<anammelu sadderan="aṭrəkka1">aṭrəkka</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aboqqa1">
		<təzugəst>aboqqa</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iboqqan</igət>
		<igət>iboqqawǎn</igət>
		<əlfiɣšǎt id="aboqqa1_1">
			<almaɣna>Amǎḍal yəẓâḍǎn yəbbât aḍu.</almaɣna>
			<təfaransist>poussière</təfaransist>
			<əlmisal>Aboqqa wər ənfa awedən n ədmarǎn.</əlmisal>
			<anammelu sadderan="ədaddəɣ1">ədaddəɣ</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abora1">
		<təzugəst>ǎbora</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iboran</igət>
		<əlfiɣšǎt id="abora1_1">
			<almaɣna>Attaɣam itâwakrazǎn dǎɣ tamert ta n jənnawǎn yolâ d ǎnǎle, yətâggu dǎɣ-əs əšənk d aɣəjira.</almaɣna>
			<təfaransist>sorgho</təfaransist>
			<əlmisal>Azzahra təcca əšənk n ǎbora yǎhâɣ ax.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="abora_n_mas_ar1">
		<təzugəst>abora-n-maṣǎr</təzugəst>
		<təmuṣt>sn-ẓwn. yy.</təmuṣt>
		<igət>iboran-ən-maṣǎr</igət>
		<əlfiɣšǎt id="abora_n_mas_ar1_1">
			<almaɣna>Attaɣam yolân əd tiɣmas, yogla ǎbora, yətâqqǎl iyaraɣǎn izaggaɣǎn, yətîmlǎl.</almaɣna>
			<təfaransist>maïs</təfaransist>
			<əlmisal>Ɣayša təkna əšənk n ǎbora-n-masar.</əlmisal>
			<anammelu>timɣas</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="abroɣ1">
		<təzugəst>abroɣ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>əbroɣǎn</igət>
		<əlfiɣšǎt id="abroɣ1_1">
			<almaɣna>Telašše təknât dǎɣ təḍuft təmmîgalǎt i ǎsameḍ.</almaɣna>
			<təfaransist>couverture</təfaransist>
			<əlmisal>Xammad Axmad yəlša abroɣ fel ǎmagal n ǎsameḍ.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="accu1">
		<təzugəst>accu</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="accu1_1">
			<almaɣna>Igi n mənsiwǎn dǎɣ tədist.</almaɣna>
			<təfaransist>manger</təfaransist>
			<əlmisal>Musa yəcca təkommart.</əlmisal>
			<anammelu sadderan="əccu1">əccu</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="adabon1">
		<təzugəst>adǎbon</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>idəbnan</igət>
		<əlfiɣšǎt id="adabon1_1">
			<almaɣna>Edǎg yəkkâlǎn.</almaɣna>
			<təfaransist>plateau</təfaransist>
			<əlmisal>Iẓənkaḍ fǎw adabon a fel nâṣṣin.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="adabon2">
		<təzugəst>adǎbon</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>idəbnan</igət>
		<əlfiɣšǎt id="adabon2_1">
			<almaɣna>Edǎg dǎɣ ǎddôkǎl ǎmǎḍal.</almaɣna>
			<təfaransist>monticule</təfaransist>
			<əlmisal>Musa yəwǎr adǎbon fel ad yənfuləl i wəlli-net.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="adabon3">
		<təzugəst>adǎbon</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>idəbnan</igət>
		<əlfiɣšǎt id="adabon3_1">
			<almaɣna>Edǎg yəkkârǎn igefǎn.</almaɣna>
			<təfaransist>erg</təfaransist>
			<əlmisal>Igati n tǎnere idəbnan a t-yəkkarǎn.</əlmisal>
			<anammelu>atabon</anammelu>
			<anəmmezrəy sadderan="etakas1">etakǎs</anəmmezrəy>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍaḍ1">
		<təzugəst>aḍaḍ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>a</əsəfsəs>
		<igət>iḍəḍwan</igət>
		<əlfiɣšǎt id="aḍaḍ1_1">
			<almaɣna>Ǝyyǎn dǎɣ səmmos ǎrǎtǎn wi n əhǎnin tawšet n əfus n ǎwedən.</almaɣna>
			<təfaransist>doigt</təfaransist>
			<əlmisal>Ǝfus n ǎwedən səmmos ḍəḍwan a yəla.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍaḍ2">
		<təzugəst>aḍaḍ</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iḍəḍwan</igət>
		<əlfiɣšǎt id="aḍaḍ2_1">
			<almaɣna>Ejwǎl ən kel-nan (Azawaɣ).</almaɣna>
			<təfaransist>marque des animaux de la tribu des kel-nan</təfaransist>
			<əlmisal>Aḍaḍ yǎmôs tewǎte təggârǎt aṣmət n əmudǎr.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍafir1">
		<təzugəst>ǎḍafir</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iḍufar</igət>
		<əlfiɣšǎt id="aḍafir1_1">
			<almaɣna>Ărǎt n esələs yəṣâwǎr awedən fəl təmiwant fel ma təffodǎy.</almaɣna>
			<təfaransist>coussin (pour aller à cheval, à dos de dromadaire ou à dos d’âne)</təfaransist>
			<əlmisal>Fatma wər təṣəwər ǎḍafir ejǎḍ-net, yewǎy-du sər-əs awen tǎfade.</əlmisal>
			<anammelu>əṣṣəḍfər</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍafir2">
		<təzugəst>ǎḍafir</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iḍufar</igət>
		<əlfiɣšǎt id="aḍafir2_1">
			<almaɣna>Almǎt ezuzər n ǎsedur əyyǎn i əššahi.</almaɣna>
			<təfaransist>casse-croûte, collation (avant de prendre le thé)</təfaransist>
			<əlmisal>Aɣali yəga s təkommart aḍafir i əššahi-net.</əlmisal>
			<anammelu sadderan="aṭṭajim1">aṭṭajim</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="adafor1">
		<təzugəst>adǎfor</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ədfar</igət>
		<igət>idəfran</igət>
		<əlfiɣšǎt id="adafor1_1">
			<almaɣna>Awa yətîṣumit awedən.</almaɣna>
			<təfaransist>oreiller, coussin</təfaransist>
			<əlmisal>Adǎfor wa n ǎgašek yofa wa n tǎbdoq.</əlmisal>
			<anammelu sadderan="as_as_s_amu1">aṣaṣṣamu</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="adaga1">
		<təzugəst>adǎga</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>idagatǎn</igət>
		<əlfiɣšǎt id="adaga1_1">
			<almaɣna>Tənafut ta yətâffu eləs tamṭət yǎrâ.</almaɣna>
			<təfaransist>cadeau, présent (pour la fiancée)</təfaransist>
			<əlmisal>Səliman yətâggu idǎgatǎn I təšlut-net.</əlmisal>
			<anammelu>təẓẓərkest</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍaggal1">
		<təzugəst>aḍaggal</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iḍulan</igət>
		<əlfiɣšǎt id="aḍaggal1_1">
			<almaɣna>Eləs wa s təzlafǎɣ yəlles medǎɣ rures.</almaɣna>
			<təfaransist>gendre</təfaransist>
			<əlmisal>Baẓo yaṣṣôka aḍaggal-net Makat.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="adagom1">
		<təzugəst>adagom</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>idagomǎn</igət>
		<igət>ədgam</igət>
		<tastəqW>ajwal</tastəqW>
		<əlfiɣšǎt id="adagom1_1">
			<təfaransist>sauterelle</təfaransist>
			<ǎkku sadderan="afarcakom1">afarcakom</ǎkku>
			<anammelu sadderan="afarcakom1">afarcakom</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="adal1">
		<təzugəst>adal</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>adalǎn</igət>
		<əlfiɣšǎt id="adal1_1">
			<almaɣna>Ǝmudǎr yolân d iji egas yogl-e, yah-e azzal, yəṭâṭṭu aɣalak.</almaɣna>
			<təfaransist>guépard</təfaransist>
			<əlmisal>Adal azzal a dǎɣ ənâqqu imudarǎn wi n yəṭâṭṭu.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="adal2">
		<təzugəst>adal</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>adalǎn</igət>
		<əlfiɣšǎt id="adal2_1">
			<almaɣna>Annabat dalen yətâlalǎn fəl aman.</almaɣna>
			<təfaransist>algue</təfaransist>
			<əlmisal>Iɣǎfawǎn ən gǎran yəwâr-tǎn adal.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="adalag1">
		<təzugəst>adalag</təzugəst>
		<təmuṣt>sn-nml.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ədlugǎn</igət>
		<əlfiɣšǎt id="adalag1_1">
			<almaɣna>Esəhussəy n alǎm meɣ ehǎn.</almaɣna>
			<təfaransist>ornement</təfaransist>
			<əlmisal>Fatima təga i ǎhǎn-net adalag n əbroɣǎn wi n əhwarǎn.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍalil1">
		<təzugəst>ǎḍalil</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>iḍulal</igət>
		<əlfiɣšǎt id="aḍalil1_1">
			<təfaransist>litham, voile</təfaransist>
			<ǎkku sadderan="alaššo1">alaššo</ǎkku>
			<əlmisal>Mina tesâgalmas ǎḍalil-net wa n kǎdewǎt təmərwen ən təṣəwət.</əlmisal>
			<anammelu sadderan="alaššo1">alaššo</anammelu>
			<anammelu sadderan="amasdod1">amǎsdod</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍalob1">
		<təzugəst>aḍalob</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>əḍlab</igət>
		<tastəqW>adalab</tastəqW>
		<əlfiɣšǎt id="aḍalob1_1">
			<almaɣna>Iyyǎt n ǎga.</almaɣna>
			<təfaransist>contenance d'une puisette</təfaransist>
			<əlmisal>Kǎrad əḍlab a fel tətâkkǎr tizəmt aman.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="adan1">
		<təzugəst>adan</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>a</əsəfsəs>
		<igət>adanǎn</igət>
		<əlfiɣšǎt id="adan1_1">
			<almaɣna>Arǎt ən təsənbebut ta tewǎyǎt edəfi dǎɣ tǎraga n əmudǎr.</almaɣna>
			<təfaransist>intestin grêle</təfaransist>
			<əlmisal>Təməsseŋwit təẓâmmu adanǎn fel a tǎn-yəgəməḍ ədəfi.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍar1">
		<təzugəst>aḍǎr</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iḍarǎn</igət>
		<əlfiɣšǎt id="aḍar1_1">
			<almaɣna>Ǝyyǎn dǎɣ əššin ǎrǎtǎn wi n fel yəbdǎd awedǎn, yətîjəwənkit sər-sǎn.</almaɣna>
			<təfaransist>pied</təfaransist>
			<əlmisal>Kurman yətâfǎrfǎr aḷǎm s ǎḍǎr-net.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍar2">
		<təzugəst>aḍǎr</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iḍarǎn</igət>
		<əlfiɣšǎt id="aḍar2_1">
			<almaɣna>Tawakat ən mawta.</almaɣna>
			<təfaransist>pneu</təfaransist>
			<əlmisal>Aḍǎr ən mawṭa yəẓgǎr.</əlmisal>
			<anammelu>tawkǎt</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍar3">
		<təzugəst>aḍǎr</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>iḍarǎn</igət>
		<əlfiɣšǎt id="aḍar3_1">
			<almaɣna>Arǎt n əṭərṭur yǎhân ammas n afay meɣ eɣazǎr.</almaɣna>
			<təfaransist>vallée</təfaransist>
			<əlmisal>Emnas fǎw ǎrân taməḍint dǎɣ ḍarǎn n Azawaɣ.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="adaras1">
		<təzugəst>adǎras</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>idərsan</igət>
		<əlfiɣšǎt id="adaras1_1">
			<almaɣna>Ešək wa dǎɣ kânnin inaḍǎn akabar yətârawǎn taɣalbǎst.</almaɣna>
			<təfaransist>myrrhe africaine</təfaransist>
			<əlmisal>Ikərman n ǎdaras yətâwann-asǎn wǎlǎt-adaras.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="adəd1">
		<təzugəst>adəd</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="adəd1_1">
			<almaɣna>Aḍḍa n talašše tošâmǎt fel ad təẓẓəl.</almaɣna>
			<təfaransist>repasser</təfaransist>
			<əlmisal>Ǝnəššešəm yətâdǎd tekaṭkǎt-in s əsəbbətər ən tǎɣert.</əlmisal>
			<anammelu>bǎkkǎt</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍəg1">
		<təzugəst>aḍəg</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="aḍəg1_1">
			<almaɣna>Igi n əmudǎr dǎɣ dat.</almaɣna>
			<təfaransist>faire avancer, faire chasser</təfaransist> <!-- chasser devant soi ? -->
			<əlmisal>Haruna yoḍǎg ehəri-net s əṣṣuk.</əlmisal>
			<anammelu>əstəɣ</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍən1">
		<təzugəst>aḍən</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="aḍən1_1">
			<almaɣna>Ešəggər n ǎrǎt.</almaɣna>
			<təfaransist>manquer, constater</təfaransist>
			<əlmisal>Ɣaṭa toḍǎn-in taɣat-net ta ɣaggalǎt.</əlmisal>
			<anammelu>ešəggər</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍən2">
		<təzugəst>aḍən</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="aḍən2_1">
			<almaɣna>Eṣənṣi n ǎrǎt dǎɣ ǎdǎg yolâɣǎn fel ma yəɣšǎd.</almaɣna>
			<təfaransist>conserver, surveiller</təfaransist>
			<əlmisal>Tamallat toḍǎn tikommaren-net fel tǎsagǎysǎgǎyt.</əlmisal>
			<anammelu>əɣbər</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍən3">
		<təzugəst>aḍən</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="aḍən3_1">
			<almaɣna>Iba n əšunəy.</almaɣna>
			<təfaransist>perdre de vue</təfaransist>
			<əlmisal>Nodǎn imijawǎn-nǎna, nəg-asǎn əmazal.</əlmisal>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍən4">
		<təzugəst>aḍən</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="aḍən4_1">
			<almaɣna>Arat idas widi megh tadənt.</almaɣna>
			<təfaransist>être tâché</təfaransist>
		</əlfiɣšǎt>
	</albab>

	<albab id="aḍər1">
		<təzugəst>aḍər</təzugəst>
		<təmuṣt>nml.</təmuṣt>
		<əlfiɣšǎt id="aḍər1_1">
			<almaɣna>Təyya n ǎrǎt dǎɣ aman ad yəgu tǎmert.</almaɣna>
			<təfaransist>tremper</təfaransist>
			<əlmisal>Inaḍǎn oḍǎrǎn igəškan-nǎsǎn dǎɣ aman.</əlmisal>
			<anammelu sadderan="səlməɣ1">səlməɣ</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="adda1">
		<təzugəst>adda</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>addatǎn</igət>
		<əlfiɣšǎt id="adda1_1">
			<almaɣna>Yey wa yerawǎn.</almaɣna>
			<təfaransist>père</təfaransist>
			<əlmisal>Adda n Musa yəkka Egadǎz.</əlmisal>
			<anammelu>abba</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="addaɣway1">
		<təzugəst>ǎddǎɣwǎy</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ǎddǎɣwǎten</igət>
		<əlfiɣšǎt id="addaɣway1_1">
			<almaɣna>Eganǎd meɣ təkma wər nəla əlqimǎt.</almaɣna>
			<təfaransist>malheur, malédiction</təfaransist>
			<əlmisal>Amaskǎso təgrǎw-tu ǎddǎɣwǎt wər nəmməkkǎn dəffər ənəbəẓ-net.</əlmisal>
			<anammelu>erk-ǎrǎt</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="addaɣway2">
		<təzugəst>ǎddǎɣwǎy</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əsəfsəs>ǎ</əsəfsəs>
		<igət>ǎddǎɣwǎten</igət>
		<əlfiɣšǎt id="addaɣway2_1">
			<almaɣna>Almǎt taḍləmt.</almaɣna>
			<təfaransist>provocation</təfaransist>
			<əlmisal>Ǝnmokal-nǎna təgrâw-tu ǎddǎɣwǎt wər nəla əddəlil.</əlmisal>
			<anammelu sadderan="taḍləmt1">taḍləmt</anammelu>
		</əlfiɣšǎt>
	</albab>

	<albab id="addaɣway3">
		<təzugəst>ǎddǎɣwǎy</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<əlfiɣšǎt id="addaɣway3_1">
			<almaɣna>Awa ittaf awedan wa ihan əššərigha.</almaɣna>
			<təfaransist>argument, version</təfaransist>
		</əlfiɣšǎt>
	</albab>

	<albab id="addal1">
		<təzugəst>ǎddǎl</təzugəst>
		<təmuṣt>sn. yy.</təmuṣt>
		<igət>ǎddǎlǎn</igət>
		<əlfiɣšǎt id="addal1_1">
			<almaɣna>Awa s gârradǎn aɣalak iman-nǎsǎn.</almaɣna>
			<təfaransist>jeu</təfaransist>
			<əlmisal>Tulǎgǎy tǎhâ ǎddǎlǎn wi n tâggin kel-təmajəq.</əlmisal>
			<anəmmezrəy>ekkənnas</anəmmezrəy>
		</əlfiɣšǎt>