<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="application/xml" href="nouchi_v6.xsl"?>
	
<!-- 
Auteur version papier : Jean-Baptiste ATSÉ N’CHO
 
Auteurs version XML : projet DiLAF
Coordinatrice : Chantal Enguehard
Responsable informatique 2010-2016 : Mathieu Mangeot

Date : 25/07/2017
Version : v1.3
Licence : Creative Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0) : http://creativecommons.org/licenses/by-nc-sa/2.0/

Publication de référence : Mathieu Mangeot & Chantal Enguehard (2013) Des dictionnaires éditoriaux aux représentations XML standardisées. Chaptre 8, livre "Ressources Lexicales : contenu, construction, utilisation, évaluation", Eds. Nuria Gala & Michael Zock, Linguisticae Investigationes Supplementa, John Benjamins Publishing, Amsterdam, Pays-Bas, 24 p.

-->

<!DOCTYPE dilaf [
<!ELEMENT dilaf (source, entrée*, biblio?)>
<!ATTLIST dilaf src CDATA #REQUIRED>
<!ATTLIST dilaf trg CDATA #REQUIRED>
<!ATTLIST dilaf version CDATA #REQUIRED>
<!ATTLIST dilaf datecreation CDATA #REQUIRED>

<!ELEMENT source (ref*, titre, auteurs, avertissement, license)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (#PCDATA)>
<!ELEMENT avertissement (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license lien CDATA #IMPLIED>

<!ELEMENT entrée (forme, cf*, phonétique?, catégorie?, syntaxe?, origine?, reference*, bloc?)>
<!ATTLIST entrée id ID #REQUIRED>

<!ELEMENT forme (#PCDATA)>
<!ELEMENT cf (#PCDATA)> 
<!ATTLIST cf cible IDREF #IMPLIED>
<!ATTLIST cf num CDATA #IMPLIED>
<!ELEMENT phonétique (#PCDATA)>
<!ELEMENT catégorie (#PCDATA)>
<!ELEMENT syntaxe (#PCDATA)>
<!ELEMENT origine (#PCDATA)>
<!ELEMENT bloc (sens+)>

<!ELEMENT sens (définition?, cf*, reference*, exemple*, proverbe*, synonyme*, antonyme*, expression*)>
<!ATTLIST sens num CDATA #REQUIRED>
<!ATTLIST sens id ID #REQUIRED>

<!ELEMENT définition (#PCDATA)>
<!ELEMENT exemple (version, reference?)+>
<!ELEMENT proverbe (version, reference?)+>
<!ATTLIST proverbe origine  CDATA #IMPLIED>
<!ELEMENT synonyme (#PCDATA)>
<!ATTLIST synonyme cible IDREF #IMPLIED>
<!ATTLIST synonyme num CDATA #IMPLIED>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression cible IDREF #IMPLIED>
<!ATTLIST expression num CDATA #IMPLIED>
<!ELEMENT antonyme (#PCDATA)>
<!ATTLIST antonyme cible IDREF #IMPLIED>
<!ATTLIST antonyme num CDATA #IMPLIED>
<!ELEMENT reference (#PCDATA)>
<!ATTLIST reference cible IDREF #IMPLIED>
<!ATTLIST reference num CDATA #IMPLIED>

<!ELEMENT version (#PCDATA)>
<!ATTLIST version lang CDATA #REQUIRED>

<!ELEMENT biblio (ref_biblio)+>
<!ELEMENT ref_biblio (court, auteurs, titre?, in?, num?, pages?, lieu?, éditeur?, année?, url*)>
<!ATTLIST ref_biblio id ID #REQUIRED>
<!ELEMENT court (#PCDATA)>
<!ELEMENT in (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT éditeur (#PCDATA)>
<!ELEMENT année (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ATTLIST url ligne CDATA #IMPLIED>     		<!-- date de mise en ligne -->
<!ATTLIST url consultation CDATA #IMPLIED>		<!-- date de consultation -->


]>

<dilaf src="nou" trg="fre" version="1.3" datecreation="25/07/2017">
	
	<source>
		<ref>Jean-Baptiste ATSÉ N’CHO. PARLONS NOUCHI et autres variétés du français en Côte d’Ivoire, 2016</ref>
		<titre>Dictionnaire nouchi-français (version juillet 2016)</titre>
		<auteurs>Jean-Baptiste ATSÉ N’CHO</auteurs>
		<avertissement>Ce document est protégé par une licence Creative commons Attribution-NonCommercial-ShareAlike 2.0 Generic (CC BY-NC-SA 2.0). Il est obligatoire d'insérer dans les copies, extraits et versions modifiées de ce fichier le texte suivant : "Ressource issue du dictionnaire dilaf_nou_fra_v1.3.xml hébergée par le site web DiLAF www.dilaf.org. Il est interdit de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier sans faire mention de la même licence ; il est interdit d'utiliser commercialement les informations issues de ce fichier, des copies de ce fichier et des versions modifiées de ce fichier. Il est autorisé de copier ce fichier, de modifier ce fichier, de partager ce fichier, les copies de ce fichier, les extraits de ce fichier et les versions modifiées de ce fichier à condition de le faire avec la même licence.</avertissement>
		<license lien="https://creativecommons.org/licenses/by-nc-sa/2.0/">
		</license>
	</source>
 
 
<entrée id="A_BANA_1">
	<forme>A BANA</forme>
	<phonétique>abana</phonétique>
	<origine>Dioula ou malinké</origine>
	<bloc>
		<sens num="1" id="A_BANA_1_1">
			<définition>C’est fini.</définition>
			<exemple>
				<version lang="nou">Match a bana.</version>
				<version lang="fre">Le match est terminé.</version>
			</exemple>
			<synonyme cible="WAWUÉ_1">WAWUÉ</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="À_CHEZ_NOUS_PAYS_1">
	<forme>À CHEZ NOUS PAYS</forme>
	<phonétique>aʃənupei</phonétique>
	<catégorie>expression</catégorie>
	<bloc>
		<sens num="1" id="À_CHEZ_NOUS_PAYS_1_1">
			<définition>Chez nous au pays, Comme on le dit chez nous.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ABATAR_1">
	<forme>ABATAR&#160;!</forme>
	<phonétique>abataʀ</phonétique>
	<catégorie>interjection</catégorie>
	<bloc>
		<sens num="1" id="ABATAR_1_1">
			<définition>Interjection pour se donner une certaine contenance avant d’agir, avant de faire quelque chose.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ABI_1">
	<forme>ABI&#160;!</forme>
	<phonétique>abi</phonétique>
	<catégorie>interjection</catégorie>
	<bloc>
		<sens num="1" id="ABI_1_1">
			<définition>Mon pote&#160;!</définition>
			<synonyme cible="ATO_1">ATO&#160;!</synonyme>
			<synonyme cible="DJO_1">DJO&#160;!</synonyme>
			<synonyme cible="TCHÊBA_1">TCHÊBA&#160;!</synonyme>
			<synonyme cible="AHOULI_1">AHOULI&#160;!</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="ABOKI_1">
	<forme>ABOKI</forme>
	<phonétique>aboki</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="ABOKI_1_1">
			<définition>Personne faisant le commerce du café au lait souvent accompagné de pain au beurre tous les matins et soirs.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ABOLO_1">
	<forme>ABOLO</forme>
	<phonétique>abolo</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="ABOLO_1_1">
			<définition>Couscous de maïs, de riz ou de banane fait en galettes rondes et molles et sucré d’origine ghanéenne.</définition>
			<synonyme cible="ATOUKPOU_1">ATOUKPOU</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="ADIBÉBÉ_1">
	<forme>ADIBÉBÉ</forme>
	<phonétique>adibebe</phonétique>
	<catégorie>nom</catégorie>
	<bloc>
		<sens num="1" id="ADIBÉBÉ_1_1">
			<définition>Pédophile.</définition>
			<reference>Meiway, "Adibébé"</reference>
		</sens>
	</bloc>
</entrée>

<entrée id="ADIGBATÉ_1">
	<forme>ADIGBATÉ</forme>
	<phonétique>adigbate</phonétique>
	<bloc>
		<sens num="1" id="ADIGBATÉ_1_1">
			<définition>Équivalent de "Agbolo", avoir une forme d’athlète.</définition>
			<synonyme cible="AGBÔLOH_1">AGBÔLOH</synonyme>
			<synonyme cible="DIGBA_1">DIGBA</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="ADJAMTALA_1">
	<forme>ADJAMTALA</forme>
	<phonétique>aʤamtala</phonétique>
	<bloc>
		<sens num="1" id="ADJAMTALA_1_1">
			<définition>Autre nom d’Adjamé, une commune du district d’Abidjan.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ADJOFAN_1">
	<forme>ADJOFAN</forme>
	<phonétique>aʤofã</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="ADJOFAN_1_1">
			<définition>Poisson décomposé et seché servant d’arôme à la sauce.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ADJOUFFOU_1">
	<forme>ADJOUFFOU</forme>
	<phonétique>aʤufu</phonétique>
	<bloc>
		<sens num="1" id="ADJOUFFOU_1_1">
			<définition>Autre nom de la capitale Abidjan.</définition>
			<exemple>
				<version lang="nou">En été, je fonce à Adjouffou pour les vacances.</version>
			</exemple>
			<synonyme cible="BABI_1">BABI</synonyme>
			<synonyme cible="AGBADI_1">AGBADI</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="ADOKAFLEH_1">
	<forme>ADOKAFLEH</forme>
	<phonétique>adokaflɛ</phonétique>
	<catégorie>nom masculin</catégorie>
	<origine>Expression dioula signifiant "Il faut porter (un vêtement), je vais voir".</origine>
	<bloc>
		<sens num="1" id="ADOKAFLEH_1_1">
			<définition>En nouchi, cela renvoie aux friperies.</définition>
			<synonyme cible="TOUTROUNOU_1">TOUTROUNOU</synonyme>
			<synonyme cible="YOUGOU-YOUGOU_1">YOUGOU-YOUGOU</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="AFFAIRAGE_1">
	<forme>AFFAIRAGE</forme>
	<phonétique>afɛʀaʒ</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="AFFAIRAGE_1_1">
			<définition>Colportage, divulgation, propagande.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AFFAIRÉ_E_1">
	<forme>AFFAIRÉ, E</forme>
	<phonétique>afɛʀe</phonétique>
	<catégorie>nom</catégorie>
	<bloc>
		<sens num="1" id="AFFAIRÉ_E_1_1">
			<définition>Quelqu’un qui fourre son nez dans les affaires d’autrui. Colporteur, calomniateur. Propagateur.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AFFAIRE_ME_PLAÎT_1">
	<forme>AFFAIRE (SON) ME PLAÎT</forme>
	<bloc>
		<sens num="1" id="AFFAIRE_ME_PLAÎT_1_1">
			<définition>J’aime ce qu’il fait. Je l’aime.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AFFAIRER_1">
	<forme>AFFAIRER (S’)</forme>
	<phonétique>safɛʀe</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="AFFAIRER_1_1">
			<définition>Se renseigner, se mettre au courant de certains faits en vue de les faire propager.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AGBADI_1">
	<forme>AGBADI</forme>
	<phonétique>agbadi</phonétique>
	<bloc>
		<sens num="1" id="AGBADI_1_1">
			<définition>Autre nom d’Abidjan, la capitale administrative de la Côte d’Ivoire.</définition>
			<synonyme cible="BABI_1">BABI</synonyme>
			<synonyme cible="ADJOUFFOU_1">ADJOUFFOU</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="AGBODIAMA_1">
	<forme>AGBODIAMA</forme>
	<phonétique>agboʤama</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="AGBODIAMA_1_1">
			<définition>Sorte d’attiéké de bonne qualité par ses grains très grossiers.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AGBÔLOH_1">
	<forme>AGBÔLOH</forme>
	<phonétique>agbɔlɔ</phonétique>
	<bloc>
		<sens num="1" id="AGBÔLOH_1_1">
			<définition>Muscles, musclé.</définition>
			<synonyme cible="ADIGBATÉ_1">ADIGBATÉ</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="AGBÔLÔTÉ_1">
	<forme>AGBÔLÔTÉ</forme>
	<phonétique>agbɔlɔte</phonétique>
	<catégorie>adjectif</catégorie>
	<bloc>
		<sens num="1" id="AGBÔLÔTÉ_1_1">
			<définition>Qui est très musclé, Très en forme (physiquement).</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AGBÔLÔZAHIN_1">
	<forme>AGBÔLÔZAHIN</forme>
	<phonétique>agbɔlɔzaɛ̃</phonétique>
	<catégorie>adjectif</catégorie>
	<bloc>
		<sens num="1" id="AGBÔLÔZAHIN_1_1">
			<définition>Très musclé.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AHOKO_1">
	<forme>AHOKO</forme>
	<phonétique>aoko</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="AHOKO_1_1">
			<définition>Nom donné à un instrument de musique polyphonique traditionnel d’origine baoulé et vulgarisé par la musicienne Antoinette Konan. Ce mot tire son sens du même nom de l’instrument et signifie en nouchi "masturbation" à cause du mouvement de va-et-vient en jouant de l’instrument. On dit aussi Frapper ahoko.</définition>
			<exemple>
				<version lang="nou">Nous tous, on frappe ahoco, mais y en a, c’est ça qui est leur go.</version>
				<reference>Garba 50</reference>
				<version lang="fre">Nous nous masturbons presque tous, mais il y a certains qui font de cette pratique leur femme.</version>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="AHOULI_1">
	<forme>AHOULI</forme>
	<phonétique>auli</phonétique>
	<bloc>
		<sens num="1" id="AHOULI_1_1">
			<définition>Mot bété signifiant&#160;: Mon frère, mon pote.</définition>
			<synonyme cible="DJO_1">DJO</synonyme>
			<synonyme cible="ABI_1">ABI</synonyme>
			<synonyme cible="ATO_1">ATO&#160;!</synonyme>
			<synonyme cible="TCHÊBA_1">TCHÊBA</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="AIMER_AFFAIRE_DE_QUELQU_UN__1">
	<forme>AIMER AFFAIRE DE QUELQU’UN</forme>
	<bloc>
		<sens num="1" id="AIMER_AFFAIRE_DE_QUELQU_UN__1_1">
			<définition>Apprécier le comportement de quelqu'un, s'intéresser à quelqu'un.</définition>
		</sens>
	</bloc>

</entrée>

<entrée id="AKÈNIN-KÈNIN_1">
	<forme>AKÈNIN-KÈNIN</forme>
	<phonétique>akɛnɛ̃kɛnɛ̃</phonétique>
	<origine>Du dioula «&#160;Kakene&#160;» pour demander la forme, la santé, comment ça va&#160;? «&#160;I kakene wa&#160;?&#160;»</origine>
	<bloc>
		<sens num="1" id="AKÈNIN-KÈNIN_1_1">
			<définition>En forme, en puissance.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AKPASMANDI_1">
	<forme>AKPASMANDI</forme>
	<phonétique>akpasmãdi</phonétique>
	<catégorie>nom</catégorie>
	<bloc>
		<sens num="1" id="AKPASMANDI_1_1">
			<définition>Personne qui aime les ragots les racontars, personne qui aime fouiner partout à la recherche de ragots. Colporteur, propagateur.</définition>
			<synonyme cible="KPAKPATO_1">KPAKPATO</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="AKWABA_1">
	<forme>AKWABA</forme>
	<phonétique>akwaba</phonétique>
	<catégorie>nom ou locution</catégorie>
	<origine>Mot d’origine Akan</origine>
	<bloc>
		<sens num="1" id="AKWABA_1_1">
			<définition>Pour dire Bienvenue ou souhaiter la bienvenue à quelqu’un, surtout à son hôte.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ALBERT_1">
	<forme>ALBERT</forme>
	<phonétique>albɛʀ</phonétique>
	<catégorie>nom propre.</catégorie>
	<bloc>
		<sens num="1" id="ALBERT_1_1">
			<définition>Campagnard, qui ne s’y connaît pas en ville.</définition>
			<synonyme cible="BRÉZO_1">BRÉZO</synonyme>
			<synonyme cible="GAOU_1">GAOU</synonyme>
			<synonyme cible="GAWA_1">GAWA</synonyme>
			<synonyme cible="GNATA_1">GNATA</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="ALLOCO_1">
	<forme>ALLOCO</forme>
	<phonétique>aloko</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="ALLOCO_1_1">
			<définition>Friture de banane plantain.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ALLOCODROME_1">
	<forme>ALLOCODROME</forme>
	<phonétique>alokodʀɔm</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="ALLOCODROME_1_1">
			<définition>Lieu où l’on consomme de l’alloco, de la friture de banane.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AMBIANCE_FACILE_1">
	<forme>AMBIANCE FACILE</forme>
	<phonétique>ãbjãsfasil</phonétique>
	<catégorie>nom</catégorie>
	<bloc>
		<sens num="1" id="AMBIANCE_FACILE_1_1">
			<définition>Le nom générique qui désigne un type de prestation musicale comportant un tambour, des bouteilles, des grelots et des chanteurs.</définition>
			<reference>Yacouba Konaté</reference>
		</sens>
	</bloc>
</entrée>

<entrée id="AMBIANCER_1">
	<forme>AMBIANCER</forme>
	<phonétique>ãbjãse</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="AMBIANCER_1_1">
			<définition>Créer une atmosphère générale, produire du plaisir dans un lieu, un endroit.</définition>
			<exemple>
				<version lang="nou">Alpha Blondy a ambiancé le maquis.</version>
				<version lang="fre">Alpha Blondy a créé une atmosphère générale dans la buvette.</version>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="ANANGO_1">
	<forme>ANANGO</forme>
	<phonétique>anãgo</phonétique>
	<catégorie>nom ou adjectif</catégorie>
	<bloc>
		<sens num="1" id="ANANGO_1_1">
			<définition>Autre nom donné aux Nigérians vivant en Côte d’Ivoire.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ANANGO_PLAN_1">
	<forme>ANANGO PLAN</forme>
	<phonétique>anãgoplã</phonétique>
	<bloc>
		<sens num="1" id="ANANGO_PLAN_1_1">
			<définition>Se dit de quelqu’un qui prend une attitude affectée ou trompeuse pour donner à voir une apparence différente de ce qu'il est ou de ce qu'il éprouve.</définition>
		</sens>
		<sens num="2" id="ANANGO_PLAN_1_2">
			<définition>Petite escroquerie, une promesse non tenue.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ANTICOS_1">
	<forme>ANTICOS</forme>
	<phonétique>ãtikɔs</phonétique>
	<catégorie>nom</catégorie>
	<bloc>
		<sens num="1" id="ANTICOS_1_1">
			<définition>Dans le langage populaire des Ivoiriens de France, mot pour désigner les Antillais.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ANTILALÉCA_1">
	<forme>ANTILALÉCA</forme>
	<phonétique>ãtilaleka</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="ANTILALÉCA_1_1">
			<définition>Produit aphrodisiaque pour (re)conquérir un homme.</définition>
			<reference cible="Yodé_Siro">Yodé &amp; Siro</reference>
			<synonyme cible="KAN-KAN-KAN_1">KAN-KAN-KAN</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="APF_1">
	<forme>APF</forme>
	<phonétique>apeɛf</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="APF_1_1">
			<définition>Sigle pour un plat d’Attiéké Poisson Fumé.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="APOLO_1">
	<forme>APOLO</forme>
	<phonétique>apolo</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="APOLO_1_1">
			<définition>Conjonctivite (maladie dont l’apparition a coïncidé avec l’arrivée sur la lune des Américains).</définition>
			<exemple>
				<version lang="nou">Moussa a eu apolo, faut pas le regarder dans les yeux.</version>
				<version lang="fre">Moussa a contracté la conjonctivite. Il ne faut pas le regarder droit dans les yeux de peur d’être contaminé.</version>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="APPATAME_1">
	<forme>APPATAME</forme>
	<phonétique>apatam</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="APPATAME_1_1">
			<définition>Sorte de paillote ou d’abri recouvert de feuille de palmier ou de cocotier servant de lieu de repos ou de consommation de la nourriture ou de l’alcool.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ARRANGER_QUELQU_UN_1">
	<forme>ARRANGER QUELQU’UN</forme>
	<phonétique>aʀãʒe</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="ARRANGER_QUELQU_UN_1_1">
			<définition>Régler son problème, lui accorder ce qu’il demande, au besoin par la triche, la combine ou le passe-droit.</définition>
			<synonyme>FAIRE COMBINE</synonyme>
			<synonyme cible="FAIRE_COULOIR_1">FAIRE COULOIR</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="ATALAKU_1">
	<forme>ATALAKU (FAIRE UN)</forme>
	<phonétique>atalaku</phonétique>
	<origine>Mot d’origine congolaise (lingala)</origine>
	<bloc>
		<sens num="1" id="ATALAKU_1_1">
			<définition>Faire l’éloge de quelqu’un.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ATCHÊGBÊH_1">
	<forme>ATCHÊGBÊH</forme>
	<phonétique>aʧɛgbɛ</phonétique>
	<bloc>
		<sens num="1" id="ATCHÊGBÊH_1_1">
			<définition>Avare, celui ou celle qui n’aime pas partager.</définition>
			<exemple>
				<version lang="nou">Ce monsieur est atchêgbêh.</version>
				<version lang="fre">Ce monsieur est un avare.</version>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="ATO_1">
	<forme>ATO&#160;!</forme>
	<phonétique>ato</phonétique>
	<origine>Mot bété</origine>
	<bloc>
		<sens num="1" id="ATO_1_1">
			<définition>Mon pote&#160;!</définition>
			<synonyme cible="ABI_1">ABI&#160;!</synonyme>
			<synonyme cible="AHOULI_1">AHOULI</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="ATÔTÔ_1">
	<forme>ATÔTÔ</forme>
	<phonétique>atɔtɔ</phonétique>
	<catégorie>nom</catégorie>
	<bloc>
		<sens num="1" id="ATÔTÔ_1_1">
			<définition>Fantôme, revenant.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="ATOUKPOU_1">
	<forme>ATOUKPOU</forme>
	<phonétique>atukpu</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="ATOUKPOU_1_1">
			<définition>Couscous de manioc fait en galettes rondes et molles.</définition>
			<synonyme cible="ABOLO_1">ABOLO</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="ATTIÉKÉ_1">
	<forme>ATTIÉKÉ</forme>
	<phonétique>aʧeke</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="ATTIÉKÉ_1_1">
			<définition>Couscous de manioc en vrac servant de nourriture de base chez certains groupes ethniques tels les Ébrié et les Adioukrou, mais devenu une nourriture nationale en Côte d’Ivoire. L’atiéké a plusieurs qualités notamment l’AGBODIAMA qui est de meilleure qualité à cause de ces gros grains.</définition>
			<cf cible="AGBODIAMA_1">AGBODIAMA</cf>
		</sens>
	</bloc>
</entrée>

<entrée id="ATTRAPER_SON_COEUR_1">
	<forme>ATTRAPER SON CŒUR</forme>
	<phonétique>atʀapesɔ̃kœʀ</phonétique>
	<catégorie>expression</catégorie>
	<bloc>
		<sens num="1" id="ATTRAPER_SON_COEUR_1_1">
			<définition>Dans le cadre d’un incident ou d’un événement malheureux, le langage populaire ivoirien l’utilise pour dire à quelqu’un de tenir bon, ne pas laisser la douleur prendre le dessus, de résister.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AWLOUAN_1">
	<forme>AWLOUAN</forme>
	<phonétique>awlчã</phonétique>
	<catégorie>nom et adjectif</catégorie>
	<origine>Mot akan pour désigner les anciens Dahoméens (Béninois).</origine>
	<bloc>
		<sens num="1" id="AWLOUAN_1_1">
			<définition>En nouchi, cela signifie (personne de mauvais comportement et de peu de confiance).</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AWOULABA_1">
	<forme>AWOULABA</forme>
	<phonétique>awulaba</phonétique>
	<catégorie>nom féminin ou adjectif</catégorie>
	<bloc>
		<sens num="1" id="AWOULABA_1_1">
			<définition>Se dit d’une femme bien en chair et forte.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="AZAHÉ_1">
	<forme>AZAHÉ&#160;!</forme>
	<phonétique>azae</phonétique>
	<catégorie>interjection onomatopéique</catégorie>
	<bloc>
		<sens num="1" id="AZAHÉ_1_1">
			<définition>Onomatopée dite à haute voix qui précède une bagarre, une dispute dans le but d’intimider son adversaire.</définition>
			<exemple>
				<version lang="nou">Azahé&#160;! Je vais finir avec gaou-là&#160;!</version>
			</exemple>
			<synonyme cible="ZÉPAPARA_1">ZÉPAPARA</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="BABI_1">
	<forme>BABI</forme>
	<phonétique>babi</phonétique>
	<bloc>
		<sens num="1" id="BABI_1_1">
			<définition>Autre nom d’Abidjan, la capitale administrative de la Côte d’Ivoire.</définition>
			<synonyme cible="AGBADI_1">AGBADI</synonyme>
			<synonyme cible="ADJOUFFOU_1">ADJOUFFOU</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="BABIÊ_1">
	<forme>BABIÊ</forme>
	<phonétique>babjɛ</phonétique>
	<catégorie>nom</catégorie>
	<origine>Langue dioula</origine>
	<bloc>
		<sens num="1" id="BABIÊ_1_1">
			<définition>Juron signifiant bâtard (sexe féminin).</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BABIÊYA_1">
	<forme>BABIÊYA</forme>
	<phonétique>babjɛja</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BABIÊYA_1_1">
			<définition>Couteau à double tranchant.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BACRÔ_1">
	<forme>BACRÔ</forme>
	<cf cible="BAKRÔ_1">BAKRÔ</cf>
	<phonétique>bakʀɔ</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="BACRÔ_1_1">
			<définition>Dormir, se reposer.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BACRÔ_2">
	<forme>BACRÔ</forme>
	<cf cible="BAKRÔ_2">BAKRÔ</cf>
	<phonétique>bakʀɔ</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BACRÔ_2_1">
			<définition>Logement, couchette, maison.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BADEF_1">
	<forme>BADEF</forme>
	<phonétique>badɛf</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BADEF_1_1">
			<définition>Pantalon aux bas larges&#160;; abréviation de bas d’éléphant.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BADJAN_1">
	<forme>BADJAN</forme>
	<phonétique>baʤã</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BADJAN_1_1">
			<définition>Autre nom du camion de 22 places servant de transport en commun dans les grandes villes.</définition>
			<synonyme cible="GBAKA_1">GBAKA</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="BADOU_1">
	<forme>BADOU</forme>
	<phonétique>badu</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="BADOU_1_1">
			<définition>Manger.</définition>
			<exemple>
				<version lang="nou">J’ai badou un zegène de 5 togos seul.</version>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="BADOUKO_1">
	<forme>BADOUKO</forme>
	<phonétique>baduko</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BADOUKO_1_1">
			<définition>Nourriture, la pitance.</définition>
			<synonyme cible="DABALI_1">DABALI</synonyme>
			<synonyme cible="GRAYA_1">GRAYA</synonyme>
			<synonyme cible="DJAFFE_1">DJAFFE</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="BADRÔ_1">
	<forme>BADRÔ</forme>
	<phonétique>badʀɔ</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="BADRÔ_1_1">
			<définition>Boire.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BAGA-BAGA_1">
	<forme>BAGA-BAGA</forme>
	<phonétique>bagabaga</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="BAGA-BAGA_1_1">
			<définition>Rouler, tourner en bourrique, tromper, ruser.</définition>
		</sens>
		<sens num="2" id="BAGA-BAGA_1_2">
			<définition>Effrayer, Faire peur.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BAGDAD_CITY_1">
	<forme>BAGDAD CITY</forme>
	<phonétique>bagdadsiti</phonétique>
	<bloc>
		<sens num="1" id="BAGDAD_CITY_1_1">
			<définition>Autre nom d’Abobo (une commune du district d’Abidjan) donné à la suite des événèments post-électoraux de 2010 avec l’apparition du commando invisible.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BAGABOU_1">
	<forme>BAGABOU (SE)</forme>
	<phonétique>səbagabu</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="BAGABOU_1_1">
			<définition>Fumer un joint.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BAGNON_1">
	<forme>BAGNON</forme>
	<phonétique>baɲɔ̃</phonétique>
	<catégorie>nom masculin</catégorie>
	<origine>Mot bété</origine>
	<bloc>
		<sens num="1" id="BAGNON_1_1">
			<définition>Joli garçon.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BAGO_ou_BARGO_1">
	<forme>BAGO ou BARGO</forme>
	<phonétique>bago</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BAGO_ou_BARGO_1_1">
			<définition>Chaussures mocassin de marque Sebago.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BAHÉFOUÊ_1">
	<forme>BAHÉFOUÊ</forme>
	<phonétique>baefwɛ</phonétique>
	<catégorie>nom et adjectif</catégorie>
	<origine>Baoulé</origine>
	<bloc>
		<sens num="1" id="BAHÉFOUÊ_1_1">
			<définition>Désigne en langue baoulé le génie de la forêt disposant de pouvoirs surnaturels. C’est aussi le nom de troupe de certains corps de l’armée ivoirienne.</définition>
		</sens>
	</bloc>
</entrée>

<entrée id="BAHI_1">
	<forme>BAHI</forme>
	<phonétique>bai</phonétique>
	<catégorie>nom ou adjectif</catégorie>
	<bloc>
		<sens num="1" id="BAHI_1_1">
			<définition>Malheur, poisse.</définition>
			<antonyme cible="DOUAHOU_1">DOUAHOU</antonyme>
			<expression cible="BAHI_2">BAHI (ÊTRE)</expression>
		</sens>
	</bloc>
</entrée>

<entrée id="BAHI_2">
	<forme>BAHI (ÊTRE)</forme>
	<cf cible="BAHI_1">BAHI</cf>
	<catégorie>expression</catégorie>
	<bloc>
		<sens num="1" id="BAHI_2_1">
			<définition>Malchanceux, Poisseux.</définition>
		</sens>
	</bloc>
</entrée>


<entrée id="BAHILOCKÉ_1">
	<forme>BAHILOCKÉ</forme>
	<phonétique>bailoke</phonétique>
	<catégorie>adjectif</catégorie>
	<origine>Vient du mot (bété) bahi «&#160;malheur, poisse&#160;» et de locké (de la déformation anglaise de lucky) «&#160;chanceux&#160;»</origine>
	<bloc>
		<sens num="1" id="BAHILOCKÉ_1_1">
			<définition>Malchanceux.</définition>
			<exemple>
				<version lang="nou">Tommy (personnage de l’hebdomadaire satirique Gbich&#160;!) est toujours bahilocké.</version>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="BAHITE_1">
	<forme>BAHITE</forme>
	<phonétique>bait</phonétique>
	<catégorie>nom féminin</catégorie>
	<origine>Déformation de bite.</origine>
	<bloc>
		<sens num="1" id="BAHITE_1_1">
			<définition>Organe sexuel masculin de la copulation, pénis.</définition>
			<exemple>
				<version lang="nou">Ce monsieur a une grosse bahite.</version>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="BAHO_1">
	<forme>BAHO</forme>
	<phonétique>bao</phonétique>
	<catégorie>verbe ou nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BAHO_1_1">
			<définition>Tuer quelqu’un avec un pistolet.</définition>
			<exemple>
				<version lang="nou">La PJ a baho le loubard du quartier.</version>
			</exemple>
		</sens>
		<sens num="2" id="BAHO_1_2">
			<définition>Pistolet, Flingue.</définition>
			<exemple>
				<version lang="nou">«&#160;Si l’État paie les uns, les autres ont les baho pour aller braquer.&#160;»</version>
				<reference>Garba 50. "On vit comme on peut"</reference>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="BAKA_1">
	<forme>BAKA</forme>
	<phonétique>baka</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BAKA_1_1">
			<définition>Bouillie à base de céréales (riz, mil notamment).</définition>
			<exemple>
				<version lang="nou">Si tu n’as rien à manger, tu peux boire baka.</version>
			</exemple>
		</sens>
	</bloc>
</entrée>

<entrée id="BAKRÔ_1">
	<forme>BAKRÔ</forme>
	<cf cible="BACRÔ_1">BACRÔ</cf>
	<phonétique>bakʀɔ</phonétique>
	<catégorie>verbe</catégorie>
	<bloc>
		<sens num="1" id="BAKRÔ_1_1">
			<définition>Dormir, se reposer.</définition>
			<synonyme cible="KRÔH_1">KRÔH</synonyme>
		</sens>
	</bloc>
</entrée>

<entrée id="BAKRÔ_2">
	<forme>BAKRÔ</forme>
	<cf cible="BACRÔ_2">BACRÔ</cf>
	<phonétique>bakʀɔ</phonétique>
	<catégorie>nom masculin</catégorie>
	<bloc>
		<sens num="1" id="BAKRÔ_2_1">